-- ============================================================================
-- Developer Mastery Hub — Esquema Supabase (Fase 1)
-- Ejecutar de corrido en el SQL Editor del dashboard de Supabase.
-- Idempotente: se puede re-ejecutar sin romper el esquema existente
-- (CREATE TABLE IF NOT EXISTS, DROP POLICY IF EXISTS, CREATE OR REPLACE).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. Tablas
-- ----------------------------------------------------------------------------

-- Perfil ligado a auth.users (se crea por trigger, ver sección 4).
CREATE TABLE IF NOT EXISTS public.profiles (
  id           uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email        text NOT NULL,
  display_name text,
  avatar_url   text,
  role         text NOT NULL DEFAULT 'student' CHECK (role IN ('admin', 'student')),
  created_at   timestamptz NOT NULL DEFAULT now()
);

-- Catálogo de cursos. `description` mapea el campo `desc` del modelo TS.
CREATE TABLE IF NOT EXISTS public.modules (
  key          text PRIMARY KEY,
  name         text NOT NULL,
  icon         text,
  badge        text,
  color        text,
  "group"      text,
  description  text,
  topics       text[] NOT NULL DEFAULT '{}',
  position     int NOT NULL DEFAULT 0,
  is_published boolean NOT NULL DEFAULT true,
  updated_at   timestamptz NOT NULL DEFAULT now()
);

-- Ejercicios por módulo.
-- `format` = ExerciseFormat (prediction, ordering, snippet-pick, bug-hunt,
-- matching, context-dropdown, true-false); NULL = legacy [INPUT_N].
-- `format_payload` = UN jsonb con el payload del formato (el cliente lo
-- deserializa al tipo concreto usando `format` como discriminador).
CREATE TABLE IF NOT EXISTS public.exercises (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  module_key       text NOT NULL REFERENCES public.modules(key) ON DELETE CASCADE,
  exercise_ref     int NOT NULL,                 -- id original dentro del módulo
  title            text NOT NULL,
  stars            int NOT NULL DEFAULT 1,
  category         text,
  step             int,
  description      text,
  objective        text,
  tags             text[] NOT NULL DEFAULT '{}',
  file_name        text,
  instruction      text,
  theory           text,
  explanation_text text,
  code_snippet     text NOT NULL,
  inputs           jsonb NOT NULL DEFAULT '{}',  -- mapa INPUT_N -> ExpectedAnswer
  complete_code    text,
  simulation       jsonb,                        -- ShellScenario (solo Bash)
  format           text,
  format_payload   jsonb,
  position         int NOT NULL DEFAULT 0,
  is_published     boolean NOT NULL DEFAULT true,
  updated_at       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT exercises_module_ref_key UNIQUE (module_key, exercise_ref)
);

-- Suscripciones del usuario a cursos (alimenta la vista "Mis Cursos").
CREATE TABLE IF NOT EXISTS public.enrollments (
  user_id        uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  module_key     text NOT NULL REFERENCES public.modules(key) ON DELETE CASCADE,
  enrolled_at    timestamptz NOT NULL DEFAULT now(),
  last_opened_at timestamptz,
  PRIMARY KEY (user_id, module_key)
);

-- Ejercicios completados por usuario.
-- Regla: "cualquier autenticado practica, pero solo suscritos guardan progreso"
-- (se fuerza en la RLS con EXISTS contra enrollments, ver sección 5).
CREATE TABLE IF NOT EXISTS public.progress (
  user_id      uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  module_key   text NOT NULL REFERENCES public.modules(key) ON DELETE CASCADE,
  exercise_ref int NOT NULL,
  completed_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, module_key, exercise_ref),
  -- Valida que el ejercicio existe en ese módulo (PLAN.md §1).
  FOREIGN KEY (module_key, exercise_ref)
    REFERENCES public.exercises (module_key, exercise_ref) ON DELETE CASCADE
);

-- "Continuar donde lo dejaste".
CREATE TABLE IF NOT EXISTS public.user_state (
  user_id             uuid PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  last_module_key     text,
  last_exercise_index int,
  updated_at          timestamptz NOT NULL DEFAULT now()
);

-- ----------------------------------------------------------------------------
-- 2. Índices
-- ----------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_exercises_module    ON public.exercises(module_key);
CREATE INDEX IF NOT EXISTS idx_exercises_published ON public.exercises(is_published) WHERE is_published;
CREATE INDEX IF NOT EXISTS idx_progress_user       ON public.progress(user_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_user    ON public.enrollments(user_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_module  ON public.enrollments(module_key);

-- ----------------------------------------------------------------------------
-- 3. Funciones helper (SECURITY DEFINER: se ejecutan como el owner y no les
--    aplica RLS, evitando recursión al leer profiles desde policies).
-- ----------------------------------------------------------------------------

-- true si el usuario autenticado tiene role = 'admin' en profiles.
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  );
$$;

-- Crea la fila de profiles al registrarse un usuario en auth.users.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, display_name)
  VALUES (NEW.id, NEW.email, NEW.raw_user_meta_data ->> 'full_name')
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

-- ----------------------------------------------------------------------------
-- 4. Trigger: alta automática de perfil
-- ----------------------------------------------------------------------------

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ----------------------------------------------------------------------------
-- 5. Row Level Security (habilitada en TODAS las tablas)
-- ----------------------------------------------------------------------------

ALTER TABLE public.profiles    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.modules     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exercises   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.progress    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_state  ENABLE ROW LEVEL SECURITY;

-- Fase 8 (B4): FORCE RLS para que las políticas se apliquen también a los
-- privilegios del owner (defensa en profundidad si se usan credenciales owner).
ALTER TABLE public.profiles    FORCE ROW LEVEL SECURITY;
ALTER TABLE public.modules     FORCE ROW LEVEL SECURITY;
ALTER TABLE public.exercises   FORCE ROW LEVEL SECURITY;
ALTER TABLE public.enrollments FORCE ROW LEVEL SECURITY;
ALTER TABLE public.progress    FORCE ROW LEVEL SECURITY;
ALTER TABLE public.user_state  FORCE ROW LEVEL SECURITY;

-- profiles: SELECT solo la propia fila (o admin); UPDATE solo la propia fila.
DROP POLICY IF EXISTS profiles_select_own_or_admin ON public.profiles;
CREATE POLICY profiles_select_own_or_admin ON public.profiles
  FOR SELECT TO authenticated
  USING (auth.uid() = id OR public.is_admin());

DROP POLICY IF EXISTS profiles_update_own ON public.profiles;
CREATE POLICY profiles_update_own ON public.profiles
  FOR UPDATE TO authenticated
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- modules: SELECT si autenticado y publicado (admin ve todo); escritura admin.
DROP POLICY IF EXISTS modules_select_published_or_admin ON public.modules;
CREATE POLICY modules_select_published_or_admin ON public.modules
  FOR SELECT TO authenticated
  USING (is_published OR public.is_admin());

DROP POLICY IF EXISTS modules_insert_admin ON public.modules;
CREATE POLICY modules_insert_admin ON public.modules
  FOR INSERT TO authenticated
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS modules_update_admin ON public.modules;
CREATE POLICY modules_update_admin ON public.modules
  FOR UPDATE TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS modules_delete_admin ON public.modules;
CREATE POLICY modules_delete_admin ON public.modules
  FOR DELETE TO authenticated
  USING (public.is_admin());

-- exercises: SELECT si autenticado y publicado (admin ve todo); escritura admin.
DROP POLICY IF EXISTS exercises_select_published_or_admin ON public.exercises;
CREATE POLICY exercises_select_published_or_admin ON public.exercises
  FOR SELECT TO authenticated
  USING (is_published OR public.is_admin());

DROP POLICY IF EXISTS exercises_insert_admin ON public.exercises;
CREATE POLICY exercises_insert_admin ON public.exercises
  FOR INSERT TO authenticated
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS exercises_update_admin ON public.exercises;
CREATE POLICY exercises_update_admin ON public.exercises
  FOR UPDATE TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS exercises_delete_admin ON public.exercises;
CREATE POLICY exercises_delete_admin ON public.exercises
  FOR DELETE TO authenticated
  USING (public.is_admin());

-- enrollments: SELECT/INSERT/DELETE solo la propia fila.
-- UPDATE solo la propia fila y, además, restringido por GRANT a la columna
-- last_opened_at (ver sección 6).
DROP POLICY IF EXISTS enrollments_select_own ON public.enrollments;
CREATE POLICY enrollments_select_own ON public.enrollments
  FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS enrollments_insert_own ON public.enrollments;
CREATE POLICY enrollments_insert_own ON public.enrollments
  FOR INSERT TO authenticated
  WITH CHECK (
    auth.uid() = user_id
    AND EXISTS (
      SELECT 1 FROM public.modules m
      WHERE m.key = enrollments.module_key AND m.is_published
    )
  );

DROP POLICY IF EXISTS enrollments_update_own ON public.enrollments;
CREATE POLICY enrollments_update_own ON public.enrollments
  FOR UPDATE TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS enrollments_delete_own ON public.enrollments;
CREATE POLICY enrollments_delete_own ON public.enrollments
  FOR DELETE TO authenticated
  USING (auth.uid() = user_id);

-- progress: SELECT solo lo propio. INSERT/UPDATE/DELETE solo si es la propia
-- fila Y existe un enrollment del mismo usuario y module_key (subquery).
-- Nota: `progress.module_key` va calificado con el nombre de la tabla para
-- referirse a la fila que se inserta/actualiza/borra (sin calificar, la
-- subquery lo resolvería contra el alias `e` y la condición sería trivial).
DROP POLICY IF EXISTS progress_select_own ON public.progress;
CREATE POLICY progress_select_own ON public.progress
  FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS progress_insert_enrolled ON public.progress;
CREATE POLICY progress_insert_enrolled ON public.progress
  FOR INSERT TO authenticated
  WITH CHECK (
    auth.uid() = user_id
    AND EXISTS (
      SELECT 1 FROM public.enrollments e
      WHERE e.user_id = auth.uid()
        AND e.module_key = progress.module_key
    )
  );

DROP POLICY IF EXISTS progress_update_enrolled ON public.progress;
CREATE POLICY progress_update_enrolled ON public.progress
  FOR UPDATE TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (
    auth.uid() = user_id
    AND EXISTS (
      SELECT 1 FROM public.enrollments e
      WHERE e.user_id = auth.uid()
        AND e.module_key = progress.module_key
    )
  );

DROP POLICY IF EXISTS progress_delete_enrolled ON public.progress;
CREATE POLICY progress_delete_enrolled ON public.progress
  FOR DELETE TO authenticated
  USING (
    auth.uid() = user_id
    AND EXISTS (
      SELECT 1 FROM public.enrollments e
      WHERE e.user_id = auth.uid()
        AND e.module_key = progress.module_key
    )
  );

-- user_state: SELECT/INSERT/UPDATE solo lo propio (sin DELETE).
DROP POLICY IF EXISTS user_state_select_own ON public.user_state;
CREATE POLICY user_state_select_own ON public.user_state
  FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS user_state_insert_own ON public.user_state;
CREATE POLICY user_state_insert_own ON public.user_state
  FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS user_state_update_own ON public.user_state;
CREATE POLICY user_state_update_own ON public.user_state
  FOR UPDATE TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- 6. Restricciones a nivel de columna (defensa en profundidad)
-- ----------------------------------------------------------------------------
-- profiles: el usuario NO puede cambiar su propio role (evita auto-escalada
-- a admin; la promoción a admin se hace manualmente desde el dashboard).
REVOKE UPDATE ON public.profiles FROM authenticated;
GRANT UPDATE (display_name, avatar_url) ON public.profiles TO authenticated;

-- enrollments: UPDATE solo permite tocar last_opened_at.
REVOKE UPDATE ON public.enrollments FROM authenticated;
GRANT UPDATE (last_opened_at) ON public.enrollments TO authenticated;

-- ----------------------------------------------------------------------------
-- 7. Fase 8 (B4): acceso anónimo nulo
-- ----------------------------------------------------------------------------
-- La app solo accede a los datos autenticada (el landing es estático); el
-- rol `anon` (clave anon-key) no debe poder leer/escribir ninguna tabla.
REVOKE ALL ON public.profiles,
            public.modules,
            public.exercises,
            public.enrollments,
            public.progress,
            public.user_state
  FROM anon;
