-- ============================================================================
-- Developer Mastery Hub — Esquema Supabase (Fase 1)
-- Ejecutar de corrido en el SQL Editor del dashboard de Supabase.
-- Idempotente: se puede re-ejecutar sin romper el esquema existente
-- (CREATE TABLE IF NOT EXISTS, DROP POLICY IF EXISTS, CREATE OR REPLACE).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. Tablas
-- ----------------------------------------------------------------------------

-- Perfil ligado a auth.users (se crea por trigger, ver sección 4).
CREATE TABLE IF NOT EXISTS public.profiles (
  id           uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email        text NOT NULL,
  display_name text,
  avatar_url   text,
  role         text NOT NULL DEFAULT 'student' CHECK (role IN ('admin', 'student')),
  created_at   timestamptz NOT NULL DEFAULT now()
);

-- Cursos padre (los grupos históricos del catálogo).
CREATE TABLE IF NOT EXISTS public.courses (
  key          text PRIMARY KEY,
  name         text NOT NULL,
  description  text,
  icon         text,
  color        text,
  position     int NOT NULL DEFAULT 0,
  is_published boolean NOT NULL DEFAULT true,
  updated_at   timestamptz NOT NULL DEFAULT now()
);

-- Módulos/temas pertenecientes a un curso padre.
-- `description` mapea el campo `desc` del modelo TS.
CREATE TABLE IF NOT EXISTS public.modules (
  key          text PRIMARY KEY,
  course_key   text NOT NULL REFERENCES public.courses(key) ON UPDATE CASCADE ON DELETE RESTRICT,
  name         text NOT NULL,
  icon         text,
  badge        text,
  color        text,
  "group"      text,
  description  text,
  topics       text[] NOT NULL DEFAULT '{}',
  position     int NOT NULL DEFAULT 0,
  is_published boolean NOT NULL DEFAULT true,
  updated_at   timestamptz NOT NULL DEFAULT now()
);

-- Compatibilidad al re-ejecutar este esquema sobre la versión anterior.
ALTER TABLE public.modules ADD COLUMN IF NOT EXISTS course_key text;

WITH grouped_modules AS (
  SELECT DISTINCT
    COALESCE("group", 'Otros') AS group_name,
    CASE COALESCE("group", 'Otros')
      WHEN 'AWS' THEN 'aws'
      WHEN 'Buenas Practicas' THEN 'best-practices'
      WHEN 'SOLID & Clean Code' THEN 'solid-clean-code'
      WHEN 'Frontend' THEN 'frontend'
      WHEN 'Backend & Datos' THEN 'backend-data'
      WHEN 'Cloud & Serverless' THEN 'cloud-serverless'
      WHEN 'DevOps & Git' THEN 'devops-git'
      WHEN 'APIs & Seguridad' THEN 'apis-security'
      WHEN 'Testing & Calidad' THEN 'testing-quality'
      WHEN 'TypeScript' THEN 'typescript'
      WHEN 'TS Arrays' THEN 'typescript-arrays'
      ELSE 'course-' || substr(md5(COALESCE("group", 'Otros')), 1, 12)
    END AS course_key
  FROM public.modules
)
INSERT INTO public.courses (key, name, position, is_published)
SELECT
  gm.course_key,
  gm.group_name,
  COALESCE((
    SELECT min(m.position)
    FROM public.modules m
    WHERE COALESCE(m."group", 'Otros') = gm.group_name
  ), 0),
  true
FROM grouped_modules gm
ON CONFLICT (key) DO NOTHING;

UPDATE public.modules
SET course_key = CASE COALESCE("group", 'Otros')
  WHEN 'AWS' THEN 'aws'
  WHEN 'Buenas Practicas' THEN 'best-practices'
  WHEN 'SOLID & Clean Code' THEN 'solid-clean-code'
  WHEN 'Frontend' THEN 'frontend'
  WHEN 'Backend & Datos' THEN 'backend-data'
  WHEN 'Cloud & Serverless' THEN 'cloud-serverless'
  WHEN 'DevOps & Git' THEN 'devops-git'
  WHEN 'APIs & Seguridad' THEN 'apis-security'
  WHEN 'Testing & Calidad' THEN 'testing-quality'
  WHEN 'TypeScript' THEN 'typescript'
  WHEN 'TS Arrays' THEN 'typescript-arrays'
  ELSE 'course-' || substr(md5(COALESCE("group", 'Otros')), 1, 12)
END
WHERE course_key IS NULL;

ALTER TABLE public.modules ALTER COLUMN course_key SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'modules_course_key_fkey'
      AND conrelid = 'public.modules'::regclass
  ) THEN
    ALTER TABLE public.modules
      ADD CONSTRAINT modules_course_key_fkey
      FOREIGN KEY (course_key) REFERENCES public.courses(key)
      ON UPDATE CASCADE ON DELETE RESTRICT;
  END IF;
END;
$$;

-- Ejercicios por módulo.
-- `format` = ExerciseFormat (prediction, ordering, snippet-pick, bug-hunt,
-- matching, context-dropdown, true-false); NULL = legacy [INPUT_N].
-- `format_payload` = UN jsonb con el payload del formato (el cliente lo
-- deserializa al tipo concreto usando `format` como discriminador).
CREATE TABLE IF NOT EXISTS public.exercises (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  module_key       text NOT NULL REFERENCES public.modules(key) ON DELETE CASCADE,
  exercise_ref     int NOT NULL,                 -- id original dentro del módulo
  title            text NOT NULL,
  stars            int NOT NULL DEFAULT 1,
  category         text,
  step             int,
  description      text,
  objective        text,
  tags             text[] NOT NULL DEFAULT '{}',
  file_name        text,
  instruction      text,
  theory           text,
  explanation_text text,
  code_snippet     text NOT NULL,
  inputs           jsonb NOT NULL DEFAULT '{}',  -- mapa INPUT_N -> ExpectedAnswer
  complete_code    text,
  simulation       jsonb,                        -- ShellScenario (solo Bash)
  format           text,
  format_payload   jsonb,
  position         int NOT NULL DEFAULT 0,
  is_published     boolean NOT NULL DEFAULT true,
  updated_at       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT exercises_module_ref_key UNIQUE (module_key, exercise_ref)
);

-- Pistas progresivas (general → concreta) para el sistema de hints pedagógicos.
-- `jsonb` mantiene el array de strings, coherente con `inputs` y `format_payload`.
ALTER TABLE public.exercises
  ADD COLUMN IF NOT EXISTS hints jsonb;

-- Suscripciones del usuario a cursos (alimenta la vista "Mis Cursos").
CREATE TABLE IF NOT EXISTS public.enrollments (
  user_id        uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  module_key     text NOT NULL REFERENCES public.modules(key) ON DELETE CASCADE,
  enrolled_at    timestamptz NOT NULL DEFAULT now(),
  last_opened_at timestamptz,
  PRIMARY KEY (user_id, module_key)
);

-- Inscripciones al curso padre. La tabla anterior se conserva temporalmente
-- para migrar datos y mantener compatibilidad con clientes aún no actualizados.
CREATE TABLE IF NOT EXISTS public.course_enrollments (
  user_id        uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  course_key     text NOT NULL REFERENCES public.courses(key) ON UPDATE CASCADE ON DELETE CASCADE,
  enrolled_at    timestamptz NOT NULL DEFAULT now(),
  last_opened_at timestamptz,
  PRIMARY KEY (user_id, course_key)
);

INSERT INTO public.course_enrollments (
  user_id, course_key, enrolled_at, last_opened_at
)
SELECT e.user_id, m.course_key, min(e.enrolled_at), max(e.last_opened_at)
FROM public.enrollments e
JOIN public.modules m ON m.key = e.module_key
GROUP BY e.user_id, m.course_key
ON CONFLICT (user_id, course_key) DO UPDATE
SET enrolled_at = LEAST(
      public.course_enrollments.enrolled_at,
      EXCLUDED.enrolled_at
    ),
    last_opened_at = CASE
      WHEN public.course_enrollments.last_opened_at IS NULL
        THEN EXCLUDED.last_opened_at
      WHEN EXCLUDED.last_opened_at IS NULL
        THEN public.course_enrollments.last_opened_at
      ELSE GREATEST(
        public.course_enrollments.last_opened_at,
        EXCLUDED.last_opened_at
      )
    END;

-- Ejercicios completados por usuario.
-- El progreso existente conserva sus claves; las nuevas escrituras requieren
-- inscripción al curso padre (ver sección 5).
CREATE TABLE IF NOT EXISTS public.progress (
  user_id      uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  module_key   text NOT NULL REFERENCES public.modules(key) ON DELETE CASCADE,
  exercise_ref int NOT NULL,
  completed_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, module_key, exercise_ref),
  -- Valida que el ejercicio existe en ese módulo (PLAN.md §1).
  FOREIGN KEY (module_key, exercise_ref)
    REFERENCES public.exercises (module_key, exercise_ref) ON DELETE CASCADE
);

-- Señal rica de repaso espaciado (SRS-ready), aditiva sobre `progress`.
-- `completed_at` se conserva como "primera vez completado"; el cliente no lo
-- envía en el upsert para no sobrescribirlo. `attempts`/`last_correct`/
-- `last_error_keys`/`last_attempt_at` alimentan el repaso de "mis fallos".
ALTER TABLE public.progress
  ADD COLUMN IF NOT EXISTS attempts        int NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS last_correct    boolean,
  ADD COLUMN IF NOT EXISTS last_error_keys jsonb,
  ADD COLUMN IF NOT EXISTS last_attempt_at timestamptz;

-- "Continuar donde lo dejaste".
CREATE TABLE IF NOT EXISTS public.user_state (
  user_id             uuid PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  last_module_key     text,
  last_exercise_index int,
  updated_at          timestamptz NOT NULL DEFAULT now()
);

-- ----------------------------------------------------------------------------
-- 2. Índices
-- ----------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_exercises_module    ON public.exercises(module_key);
CREATE INDEX IF NOT EXISTS idx_exercises_published ON public.exercises(is_published) WHERE is_published;
CREATE INDEX IF NOT EXISTS idx_modules_course      ON public.modules(course_key);
CREATE INDEX IF NOT EXISTS idx_progress_user       ON public.progress(user_id);
CREATE INDEX IF NOT EXISTS idx_progress_user_attempt
  ON public.progress (user_id, last_attempt_at DESC);
CREATE INDEX IF NOT EXISTS idx_enrollments_user    ON public.enrollments(user_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_module  ON public.enrollments(module_key);
CREATE INDEX IF NOT EXISTS idx_course_enrollments_user
  ON public.course_enrollments(user_id);
CREATE INDEX IF NOT EXISTS idx_course_enrollments_course
  ON public.course_enrollments(course_key);

-- ----------------------------------------------------------------------------
-- 3. Funciones helper (SECURITY DEFINER: se ejecutan como el owner y no les
--    aplica RLS, evitando recursión al leer profiles desde policies).
-- ----------------------------------------------------------------------------

-- true si el usuario autenticado tiene role = 'admin' en profiles.
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  );
$$;

-- Crea la fila de profiles al registrarse un usuario en auth.users.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, display_name)
  VALUES (NEW.id, NEW.email, NEW.raw_user_meta_data ->> 'full_name')
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

-- ----------------------------------------------------------------------------
-- 4. Trigger: alta automática de perfil
-- ----------------------------------------------------------------------------

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ----------------------------------------------------------------------------
-- 5. Row Level Security (habilitada en TODAS las tablas)
-- ----------------------------------------------------------------------------

ALTER TABLE public.profiles    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.courses     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.modules     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exercises   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.course_enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.progress    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_state  ENABLE ROW LEVEL SECURITY;

-- Fase 8 (B4): FORCE RLS para que las políticas se apliquen también a los
-- privilegios del owner (defensa en profundidad si se usan credenciales owner).
ALTER TABLE public.profiles    FORCE ROW LEVEL SECURITY;
ALTER TABLE public.courses     FORCE ROW LEVEL SECURITY;
ALTER TABLE public.modules     FORCE ROW LEVEL SECURITY;
ALTER TABLE public.exercises   FORCE ROW LEVEL SECURITY;
ALTER TABLE public.enrollments FORCE ROW LEVEL SECURITY;
ALTER TABLE public.course_enrollments FORCE ROW LEVEL SECURITY;
ALTER TABLE public.progress    FORCE ROW LEVEL SECURITY;
ALTER TABLE public.user_state  FORCE ROW LEVEL SECURITY;

-- profiles: SELECT solo la propia fila (o admin); UPDATE solo la propia fila.
DROP POLICY IF EXISTS profiles_select_own_or_admin ON public.profiles;
CREATE POLICY profiles_select_own_or_admin ON public.profiles
  FOR SELECT TO authenticated
  USING (auth.uid() = id OR public.is_admin());

DROP POLICY IF EXISTS profiles_update_own ON public.profiles;
CREATE POLICY profiles_update_own ON public.profiles
  FOR UPDATE TO authenticated
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- courses: catálogo publicado visible públicamente; escritura solo admin.
DROP POLICY IF EXISTS courses_select_published_or_admin ON public.courses;
CREATE POLICY courses_select_published_or_admin ON public.courses
  FOR SELECT TO anon, authenticated
  USING (is_published OR public.is_admin());

DROP POLICY IF EXISTS courses_insert_admin ON public.courses;
CREATE POLICY courses_insert_admin ON public.courses
  FOR INSERT TO authenticated
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS courses_update_admin ON public.courses;
CREATE POLICY courses_update_admin ON public.courses
  FOR UPDATE TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS courses_delete_admin ON public.courses;
CREATE POLICY courses_delete_admin ON public.courses
  FOR DELETE TO authenticated
  USING (public.is_admin());

-- modules: SELECT si autenticado y publicado (admin ve todo); escritura admin.
DROP POLICY IF EXISTS modules_select_published_or_admin ON public.modules;
CREATE POLICY modules_select_published_or_admin ON public.modules
  FOR SELECT TO authenticated
  USING (is_published OR public.is_admin());

DROP POLICY IF EXISTS modules_insert_admin ON public.modules;
CREATE POLICY modules_insert_admin ON public.modules
  FOR INSERT TO authenticated
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS modules_update_admin ON public.modules;
CREATE POLICY modules_update_admin ON public.modules
  FOR UPDATE TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS modules_delete_admin ON public.modules;
CREATE POLICY modules_delete_admin ON public.modules
  FOR DELETE TO authenticated
  USING (public.is_admin());

-- exercises: contenido completo solo para admin o usuario inscrito al curso.
DROP POLICY IF EXISTS exercises_select_published_or_admin ON public.exercises;
DROP POLICY IF EXISTS exercises_select_enrolled_or_admin ON public.exercises;
CREATE POLICY exercises_select_enrolled_or_admin ON public.exercises
  FOR SELECT TO authenticated
  USING (
    public.is_admin()
    OR (
      exercises.is_published
      AND EXISTS (
        SELECT 1
        FROM public.modules m
        JOIN public.courses c ON c.key = m.course_key
        JOIN public.course_enrollments ce
          ON ce.course_key = m.course_key
         AND ce.user_id = (SELECT auth.uid())
        WHERE m.key = exercises.module_key
          AND m.is_published
          AND c.is_published
      )
    )
  );

DROP POLICY IF EXISTS exercises_insert_admin ON public.exercises;
CREATE POLICY exercises_insert_admin ON public.exercises
  FOR INSERT TO authenticated
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS exercises_update_admin ON public.exercises;
CREATE POLICY exercises_update_admin ON public.exercises
  FOR UPDATE TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS exercises_delete_admin ON public.exercises;
CREATE POLICY exercises_delete_admin ON public.exercises
  FOR DELETE TO authenticated
  USING (public.is_admin());

-- enrollments: SELECT/INSERT/DELETE solo la propia fila.
-- UPDATE solo la propia fila y, además, restringido por GRANT a la columna
-- last_opened_at (ver sección 6).
DROP POLICY IF EXISTS enrollments_select_own ON public.enrollments;
CREATE POLICY enrollments_select_own ON public.enrollments
  FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS enrollments_insert_own ON public.enrollments;
CREATE POLICY enrollments_insert_own ON public.enrollments
  FOR INSERT TO authenticated
  WITH CHECK (
    auth.uid() = user_id
    AND EXISTS (
      SELECT 1 FROM public.modules m
      WHERE m.key = enrollments.module_key AND m.is_published
    )
  );

DROP POLICY IF EXISTS enrollments_update_own ON public.enrollments;
CREATE POLICY enrollments_update_own ON public.enrollments
  FOR UPDATE TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS enrollments_delete_own ON public.enrollments;
CREATE POLICY enrollments_delete_own ON public.enrollments
  FOR DELETE TO authenticated
  USING (auth.uid() = user_id);

-- course_enrollments: el usuario administra su propia inscripción.
DROP POLICY IF EXISTS course_enrollments_select_own_or_admin
  ON public.course_enrollments;
CREATE POLICY course_enrollments_select_own_or_admin
  ON public.course_enrollments
  FOR SELECT TO authenticated
  USING ((SELECT auth.uid()) = user_id OR public.is_admin());

DROP POLICY IF EXISTS course_enrollments_insert_own
  ON public.course_enrollments;
CREATE POLICY course_enrollments_insert_own
  ON public.course_enrollments
  FOR INSERT TO authenticated
  WITH CHECK (
    (SELECT auth.uid()) = user_id
    AND EXISTS (
      SELECT 1 FROM public.courses c
      WHERE c.key = course_enrollments.course_key
        AND c.is_published
    )
  );

DROP POLICY IF EXISTS course_enrollments_update_own
  ON public.course_enrollments;
CREATE POLICY course_enrollments_update_own
  ON public.course_enrollments
  FOR UPDATE TO authenticated
  USING ((SELECT auth.uid()) = user_id)
  WITH CHECK ((SELECT auth.uid()) = user_id);

DROP POLICY IF EXISTS course_enrollments_delete_own
  ON public.course_enrollments;
CREATE POLICY course_enrollments_delete_own
  ON public.course_enrollments
  FOR DELETE TO authenticated
  USING ((SELECT auth.uid()) = user_id);

-- progress: las filas existentes se conservan. Escribir requiere inscripción
-- al curso padre del módulo.
DROP POLICY IF EXISTS progress_select_own ON public.progress;
CREATE POLICY progress_select_own ON public.progress
  FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS progress_insert_enrolled ON public.progress;
CREATE POLICY progress_insert_enrolled ON public.progress
  FOR INSERT TO authenticated
  WITH CHECK (
    (SELECT auth.uid()) = user_id
    AND EXISTS (
      SELECT 1
      FROM public.modules m
      JOIN public.course_enrollments ce
        ON ce.course_key = m.course_key
       AND ce.user_id = (SELECT auth.uid())
      WHERE m.key = progress.module_key
    )
  );

DROP POLICY IF EXISTS progress_update_enrolled ON public.progress;
CREATE POLICY progress_update_enrolled ON public.progress
  FOR UPDATE TO authenticated
  USING ((SELECT auth.uid()) = user_id)
  WITH CHECK (
    (SELECT auth.uid()) = user_id
    AND EXISTS (
      SELECT 1
      FROM public.modules m
      JOIN public.course_enrollments ce
        ON ce.course_key = m.course_key
       AND ce.user_id = (SELECT auth.uid())
      WHERE m.key = progress.module_key
    )
  );

DROP POLICY IF EXISTS progress_delete_enrolled ON public.progress;
CREATE POLICY progress_delete_enrolled ON public.progress
  FOR DELETE TO authenticated
  USING (
    (SELECT auth.uid()) = user_id
    AND EXISTS (
      SELECT 1
      FROM public.modules m
      JOIN public.course_enrollments ce
        ON ce.course_key = m.course_key
       AND ce.user_id = (SELECT auth.uid())
      WHERE m.key = progress.module_key
    )
  );

-- user_state: SELECT/INSERT/UPDATE solo lo propio (sin DELETE).
DROP POLICY IF EXISTS user_state_select_own ON public.user_state;
CREATE POLICY user_state_select_own ON public.user_state
  FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS user_state_insert_own ON public.user_state;
CREATE POLICY user_state_insert_own ON public.user_state
  FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS user_state_update_own ON public.user_state;
CREATE POLICY user_state_update_own ON public.user_state
  FOR UPDATE TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Catálogo público seguro: expone temario y metadatos, nunca contenido que
-- revele código, respuestas o soluciones.
CREATE OR REPLACE FUNCTION public.get_public_course_curriculum(
  p_course_key text DEFAULT NULL
)
RETURNS TABLE (
  course_key text,
  course_name text,
  course_description text,
  course_icon text,
  course_color text,
  course_position int,
  curriculum jsonb
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT
    c.key,
    c.name,
    c.description,
    c.icon,
    c.color,
    c.position,
    COALESCE(
      jsonb_agg(
        jsonb_build_object(
          'key', m.key,
          'name', m.name,
          'icon', m.icon,
          'badge', m.badge,
          'color', m.color,
          'description', m.description,
          'topics', m.topics,
          'position', m.position,
          'exercises', (
            SELECT COALESCE(
              jsonb_agg(
                jsonb_build_object(
                  'exercise_ref', e.exercise_ref,
                  'title', e.title,
                  'stars', e.stars,
                  'category', e.category,
                  'step', e.step,
                  'description', e.description,
                  'objective', e.objective,
                  'tags', e.tags,
                  'position', e.position
                )
                ORDER BY e.position, e.exercise_ref
              ),
              '[]'::jsonb
            )
            FROM public.exercises e
            WHERE e.module_key = m.key
              AND e.is_published
          )
        )
        ORDER BY m.position, m.key
      ) FILTER (WHERE m.key IS NOT NULL),
      '[]'::jsonb
    )
  FROM public.courses c
  LEFT JOIN public.modules m
    ON m.course_key = c.key
   AND m.is_published
  WHERE c.is_published
    AND (p_course_key IS NULL OR c.key = p_course_key)
  GROUP BY c.key, c.name, c.description, c.icon, c.color, c.position
  ORDER BY c.position, c.key;
$$;

-- ----------------------------------------------------------------------------
-- 6. Restricciones a nivel de columna (defensa en profundidad)
-- ----------------------------------------------------------------------------
-- profiles: el usuario NO puede cambiar su propio role (evita auto-escalada
-- a admin; la promoción a admin se hace manualmente desde el dashboard).
REVOKE UPDATE ON public.profiles FROM authenticated;
GRANT UPDATE (display_name, avatar_url) ON public.profiles TO authenticated;

-- enrollments: UPDATE solo permite tocar last_opened_at.
REVOKE UPDATE ON public.enrollments FROM authenticated;
GRANT UPDATE (last_opened_at) ON public.enrollments TO authenticated;

-- Objetos de la jerarquía: revocación explícita y permisos mínimos.
REVOKE ALL ON public.courses,
              public.course_enrollments
  FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.courses TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.courses TO authenticated;
GRANT SELECT, INSERT, DELETE ON public.course_enrollments TO authenticated;
GRANT UPDATE (last_opened_at) ON public.course_enrollments TO authenticated;

REVOKE EXECUTE ON FUNCTION public.get_public_course_curriculum(text)
  FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_public_course_curriculum(text)
  TO anon, authenticated;

-- ----------------------------------------------------------------------------
-- 7. Acceso anónimo restringido al catálogo público
-- ----------------------------------------------------------------------------
-- `anon` solo puede leer cursos publicados y ejecutar el RPC público.
REVOKE ALL ON public.profiles,
            public.modules,
            public.exercises,
            public.enrollments,
            public.course_enrollments,
            public.progress,
            public.user_state
  FROM anon;
