// ══════════════════════════════════════════════════════════════════════════════
// DEVELOPER MASTERY HUB — Banco de Ejercicios por Módulo
// Preparación Full Stack Senior: Vue 3, Firebase, TS, SQL, Testing, Security,
// APIs, Pinia, Node.js, E2E, Git/DevOps, HTML5/CSS3
// ══════════════════════════════════════════════════════════════════════════════

// ─── VUE 3 COMPOSITION API (10 EJERCICIOS) ──────────────────────────────────
const VUE_EXERCISES = [
  { id: 1, title: "Ref y Reactividad Básica", stars: 1, category: "REFS", description: "Crea un contador reactivo con ref(). Si es par se muestra verde, impar rojo.", objective: "ref() y computed()", tags: ["ref", "computed", ":class"], fileName: "Counter.vue", completed: false, explanationText: "ref() envuelve un primitivo en un objeto reactivo. computed() se recalcula automáticamente cuando sus dependencias cambian.", codeSnippet: "<script setup>\nimport { [INPUT_1], computed } from 'vue';\n\nconst count = [INPUT_2](0);\nconst isEven = computed(() => count.[INPUT_3] % 2 === 0);\nconst increment = () => count.[INPUT_4]++;\n<\/script>", inputs: { INPUT_1: "ref", INPUT_2: "ref", INPUT_3: "value", INPUT_4: "value" }, completeCode: "import { ref, computed } from 'vue';\nconst count = ref(0);\nconst isEven = computed(() => count.value % 2 === 0);\nconst increment = () => count.value++;" },
  { id: 2, title: "Binding de Estilos Dinámicos", stars: 1, category: "BINDINGS", description: "Controla el estilo CSS de un elemento usando :style con un objeto reactivo.", objective: ":style con objetos JS dinámicos", tags: [":style", "boolean", "reactividad"], fileName: "Lamp.vue", completed: false, explanationText: "Vue permite enlazar objetos JS directamente al atributo style. Los valores reactivos actualizan el DOM automáticamente.", codeSnippet: "<div [INPUT_1]=\"{ backgroundColor: isOn ? '#fef08a' : '#1f2937' }\">\n</div>\n<button @click=\"[INPUT_2]\">\n  Toggle\n</button>\n\n<script setup>\nimport { [INPUT_3] } from 'vue';\nconst isOn = ref(false);\nconst toggle = () => isOn.[INPUT_4] = !isOn.value;\n<\/script>", inputs: { INPUT_1: ":style", INPUT_2: "toggle", INPUT_3: "ref", INPUT_4: "value" }, completeCode: ":style=\"{ backgroundColor: isOn ? '#fef08a' : '#1f2937' }\"\ntoggle = () => isOn.value = !isOn.value;" },
  { id: 3, title: "v-model y Filtrado Reactivo", stars: 2, category: "BINDINGS", description: "Sincroniza un input con ref usando v-model y filtra una lista con computed.", objective: "v-model bidireccional", tags: ["v-model", "computed", "filter"], fileName: "Search.vue", completed: false, explanationText: "v-model es azúcar sintáctica que combina :value y @input. computed recalcula el filtrado automáticamente al escribir.", codeSnippet: "<input [INPUT_1]=\"query\" />\n<li v-for=\"item in filtered\" :key=\"item\">{{ item }}</li>\n\n<script setup>\nimport { ref, [INPUT_2] } from 'vue';\nconst items = ['Vue', 'React', 'Angular'];\nconst query = ref('');\nconst filtered = [INPUT_3](() =>\n  items.filter(i => i.toLowerCase().includes(query.[INPUT_4].toLowerCase()))\n);\n<\/script>", inputs: { INPUT_1: "v-model", INPUT_2: "computed", INPUT_3: "computed", INPUT_4: "value" }, completeCode: "v-model=\"query\"\nconst filtered = computed(() => items.filter(...));" },
  { id: 4, title: "defineEmits: Eventos Hijo → Padre", stars: 2, category: "EMITS", description: "El hijo emite un evento personalizado al padre sin gestionar estado propio.", objective: "defineEmits() para comunicación ascendente", tags: ["defineEmits", "emit", "$emit"], fileName: "LikeButton.vue", completed: false, explanationText: "defineEmits declara los eventos que un componente puede emitir. El padre escucha con @nombre-evento.", codeSnippet: "<button @click=\"[INPUT_1]\">Like</button>\n\n<script setup>\nconst emit = [INPUT_2]<{\n  (e: 'on-like'): void\n}>();\nconst doLike = () => [INPUT_3]('on-like');\n<\/script>", inputs: { INPUT_1: "doLike", INPUT_2: "defineEmits", INPUT_3: "emit" }, completeCode: "const emit = defineEmits();\nemit('on-like');" },
  { id: 5, title: "defineProps con TypeScript", stars: 2, category: "PROPS", description: "Recibe props tipadas desde el padre usando defineProps con genéricos de TypeScript.", objective: "Props tipadas con defineProps<T>()", tags: ["defineProps", "TypeScript", "interface"], fileName: "UserCard.vue", completed: false, explanationText: "defineProps<T>() permite tipar las props directamente con una interfaz de TypeScript, sin necesidad de la sintaxis de objeto.", codeSnippet: "<script setup lang=\"ts\">\ninterface Props {\n  name: [INPUT_1];\n  age: [INPUT_2];\n  email?: string;\n}\nconst props = [INPUT_3]<Props>();\n<\/script>\n<template>\n  <p>{{ props.[INPUT_4] }} - {{ props.age }}</p>\n</template>", inputs: { INPUT_1: "string", INPUT_2: "number", INPUT_3: "defineProps", INPUT_4: "name" }, completeCode: "const props = defineProps<Props>();" },
  { id: 6, title: "watch y watchEffect", stars: 3, category: "WATCHERS", description: "Observa cambios en un ref con watch() para ejecutar side-effects cuando el valor cambie.", objective: "Diferencia entre watch y watchEffect", tags: ["watch", "watchEffect", "side-effect"], fileName: "Watcher.vue", completed: false, explanationText: "watch() vigila fuentes específicas y recibe old/new values. watchEffect() se ejecuta inmediatamente y rastrea sus dependencias.", codeSnippet: "import { ref, [INPUT_1] } from 'vue';\n\nconst query = ref('');\n\n[INPUT_2](query, ([INPUT_3], oldVal) => {\n  console.log('Cambió de', oldVal, 'a', [INPUT_4]);\n});", inputs: { INPUT_1: "watch", INPUT_2: "watch", INPUT_3: "newVal", INPUT_4: "newVal" }, completeCode: "watch(query, (newVal, oldVal) => {\n  console.log('Cambió de', oldVal, 'a', newVal);\n});" },
  { id: 7, title: "Lifecycle Hooks: onMounted", stars: 2, category: "LIFECYCLE", description: "Usa onMounted para ejecutar código después de que el componente se monta en el DOM.", objective: "Hooks del ciclo de vida en Composition API", tags: ["onMounted", "onUnmounted", "lifecycle"], fileName: "Lifecycle.vue", completed: false, explanationText: "onMounted se ejecuta una vez que el componente y sus hijos están en el DOM. Ideal para fetch de datos iniciales o suscripciones.", codeSnippet: "import { ref, [INPUT_1] } from 'vue';\n\nconst data = ref(null);\n\n[INPUT_2]([INPUT_3] () => {\n  const res = await fetch('/api/data');\n  data.value = await res.[INPUT_4]();\n});", inputs: { INPUT_1: "onMounted", INPUT_2: "onMounted", INPUT_3: "async", INPUT_4: "json" }, completeCode: "onMounted(async () => {\n  const res = await fetch('/api/data');\n  data.value = await res.json();\n});" },
  { id: 8, title: "provide / inject: Inyección de Dependencias", stars: 3, category: "DI", description: "Provee datos desde un ancestro a componentes nietos sin pasar props intermedias.", objective: "Patrón provide/inject en Vue 3", tags: ["provide", "inject", "DI"], fileName: "ThemeProvider.vue", completed: false, explanationText: "provide/inject permite compartir datos entre componentes sin importar la profundidad del árbol, similar a la inyección de dependencias en .NET.", codeSnippet: "// Padre\nimport { [INPUT_1] } from 'vue';\n[INPUT_2]('theme', 'dark');\n\n// Nieto\nimport { [INPUT_3] } from 'vue';\nconst theme = [INPUT_4]('theme', 'light');", inputs: { INPUT_1: "provide", INPUT_2: "provide", INPUT_3: "inject", INPUT_4: "inject" }, completeCode: "provide('theme', 'dark');\nconst theme = inject('theme', 'light');" },
  { id: 9, title: "Composables: Lógica Reutilizable", stars: 4, category: "COMPOSABLES", description: "Extrae lógica reactiva reutilizable en una función composable (useCounter).", objective: "Crear composables personalizados", tags: ["composable", "use*", "reutilización"], fileName: "useCounter.ts", completed: false, explanationText: "Los composables son funciones que encapsulan lógica reactiva. Siguen la convención use* y retornan refs/methods reutilizables.", codeSnippet: "import { [INPUT_1], computed } from 'vue';\n\nexport function [INPUT_2]() {\n  const count = ref(0);\n  const double = computed(() => count.value * 2);\n  const increment = () => count.[INPUT_3]++;\n  return { count, double, [INPUT_4] };\n}", inputs: { INPUT_1: "ref", INPUT_2: "useCounter", INPUT_3: "value", INPUT_4: "increment" }, completeCode: "export function useCounter() {\n  const count = ref(0);\n  const double = computed(() => count.value * 2);\n  const increment = () => count.value++;\n  return { count, double, increment };\n}" },
  { id: 10, title: "Slots con nombre y Scoped Slots", stars: 4, category: "SLOTS", description: "Usa slots con nombre para proyectar contenido flexible en componentes reutilizables.", objective: "Named slots y scoped slots", tags: ["slot", "v-slot", "template"], fileName: "Card.vue", completed: false, explanationText: "Los named slots permiten definir múltiples puntos de inserción de contenido. Scoped slots exponen datos del hijo al padre.", codeSnippet: "<!-- Card.vue -->\n<div class=\"card\">\n  <header><[INPUT_1] name=\"header\" /></header>\n  <main><slot /></main>\n</div>\n\n<!-- Uso -->\n<Card>\n  <[INPUT_2] [INPUT_3]=\"header\">\n    <h2>Título</h2>\n  </template>\n  <p>Contenido [INPUT_4]</p>\n</Card>", inputs: { INPUT_1: "slot", INPUT_2: "template", INPUT_3: "v-slot", INPUT_4: "default" }, completeCode: "<slot name=\"header\" />\n<template v-slot:header>...</template>" }
];

// ─── PINIA STATE MANAGEMENT (8 EJERCICIOS) ──────────────────────────────────
const PINIA_EXERCISES = [
  { id: 1, title: "Definir un Store con defineStore", stars: 1, category: "SETUP", description: "Crea tu primer store de Pinia usando la sintaxis de setup (Composition API style).", objective: "defineStore() con setup function", tags: ["defineStore", "Pinia", "store"], fileName: "useAuthStore.ts", completed: false, explanationText: "defineStore recibe un id único y una función setup que retorna state, getters y actions como refs y funciones normales.", codeSnippet: "import { [INPUT_1] } from 'pinia';\nimport { ref, computed } from 'vue';\n\nexport const useAuthStore = [INPUT_2]('auth', () => {\n  const user = [INPUT_3](null);\n  const isLoggedIn = computed(() => user.value !== null);\n  return { user, [INPUT_4] };\n});", inputs: { INPUT_1: "defineStore", INPUT_2: "defineStore", INPUT_3: "ref", INPUT_4: "isLoggedIn" }, completeCode: "export const useAuthStore = defineStore('auth', () => {\n  const user = ref(null);\n  const isLoggedIn = computed(() => user.value !== null);\n  return { user, isLoggedIn };\n});" },
  { id: 2, title: "State: Acceso y Mutación Reactiva", stars: 1, category: "STATE", description: "Accede al estado del store desde un componente y muta valores directamente.", objective: "Leer y mutar state de Pinia", tags: ["state", "$patch", "mutación"], fileName: "Profile.vue", completed: false, explanationText: "En Pinia el state es reactivo. Puedes mutar propiedades directamente o usar $patch para cambios en lote.", codeSnippet: "import { useAuthStore } from './stores/auth';\n\nconst store = [INPUT_1]();\n\n// Acceder al estado\nconsole.log(store.[INPUT_2]);\n\n// Mutar directamente\nstore.user = { name: 'Iram' };\n\n// Patch en lote\nstore.[INPUT_3]({ user: null });", inputs: { INPUT_1: "useAuthStore", INPUT_2: "user", INPUT_3: "$patch" }, completeCode: "const store = useAuthStore();\nstore.$patch({ user: null });" },
  { id: 3, title: "Getters: Propiedades Computadas del Store", stars: 2, category: "GETTERS", description: "Define getters que calculan valores derivados del estado del store.", objective: "Getters como computed del store", tags: ["getters", "computed", "derivado"], fileName: "useCartStore.ts", completed: false, explanationText: "Los getters en Pinia son equivalentes a computed. Se cachean y solo recalculan cuando sus dependencias cambian.", codeSnippet: "export const useCartStore = defineStore('cart', () => {\n  const items = ref([]);\n  \n  const totalPrice = [INPUT_1](() =>\n    items.value.[INPUT_2]((sum, item) => sum + item.price, 0)\n  );\n  \n  const itemCount = computed(() => items.value.[INPUT_3]);\n  \n  return { items, totalPrice, [INPUT_4] };\n});", inputs: { INPUT_1: "computed", INPUT_2: "reduce", INPUT_3: "length", INPUT_4: "itemCount" }, completeCode: "const totalPrice = computed(() => items.value.reduce((sum, i) => sum + i.price, 0));" },
  { id: 4, title: "Actions: Lógica Asíncrona en el Store", stars: 3, category: "ACTIONS", description: "Define actions asíncronas para hacer fetch de datos y actualizar el estado.", objective: "Actions con async/await", tags: ["actions", "async", "fetch"], fileName: "useProductStore.ts", completed: false, explanationText: "Las actions en Pinia pueden ser asíncronas. Son funciones normales que mutan el state después de operaciones externas.", codeSnippet: "export const useProductStore = defineStore('products', () => {\n  const products = ref([]);\n  const loading = ref(false);\n  \n  const fetchProducts = [INPUT_1] () => {\n    loading.value = true;\n    const res = [INPUT_2] fetch('/api/products');\n    products.value = await res.[INPUT_3]();\n    loading.value = [INPUT_4];\n  };\n  \n  return { products, loading, fetchProducts };\n});", inputs: { INPUT_1: "async", INPUT_2: "await", INPUT_3: "json", INPUT_4: "false" }, completeCode: "const fetchProducts = async () => {\n  loading.value = true;\n  const res = await fetch('/api/products');\n  products.value = await res.json();\n  loading.value = false;\n};" },
  { id: 5, title: "storeToRefs: Desestructurar sin perder reactividad", stars: 2, category: "HELPERS", description: "Usa storeToRefs para desestructurar state/getters del store sin perder reactividad.", objective: "storeToRefs vs desestructuración directa", tags: ["storeToRefs", "destructuring", "reactivity"], fileName: "Component.vue", completed: false, explanationText: "Desestructurar un store directamente pierde reactividad. storeToRefs convierte cada propiedad en un ref independiente.", codeSnippet: "import { [INPUT_1] } from 'pinia';\nimport { useCartStore } from './stores/cart';\n\nconst store = useCartStore();\nconst { items, totalPrice } = [INPUT_2](store);\nconst { [INPUT_3] } = store; // Actions se desestructuran [INPUT_4]", inputs: { INPUT_1: "storeToRefs", INPUT_2: "storeToRefs", INPUT_3: "addItem", INPUT_4: "directo" }, completeCode: "const { items, totalPrice } = storeToRefs(store);\nconst { addItem } = store;" },
  { id: 6, title: "$subscribe: Escuchar Cambios del Store", stars: 3, category: "WATCHERS", description: "Suscríbete a mutaciones del store para ejecutar side-effects como persistencia.", objective: "Reaccionar a cambios de estado", tags: ["$subscribe", "mutation", "persistence"], fileName: "persistence.ts", completed: false, explanationText: "$subscribe escucha cualquier cambio en el state del store, ideal para sincronizar con localStorage o APIs externas.", codeSnippet: "const cartStore = useCartStore();\n\ncartStore.[INPUT_1]((mutation, state) => {\n  localStorage.[INPUT_2](\n    'cart',\n    JSON.[INPUT_3](state.items)\n  );\n});", inputs: { INPUT_1: "$subscribe", INPUT_2: "setItem", INPUT_3: "stringify" }, completeCode: "cartStore.$subscribe((mutation, state) => {\n  localStorage.setItem('cart', JSON.stringify(state.items));\n});" },
  { id: 7, title: "$reset: Restaurar Estado Inicial", stars: 2, category: "HELPERS", description: "Reinicia el store a su estado inicial usando $reset() (solo en Options API stores).", objective: "Reset de estado del store", tags: ["$reset", "initial", "state"], fileName: "Logout.vue", completed: false, explanationText: "En stores con Options API, $reset() restaura todos los valores al estado inicial. En Setup stores debes crear tu propia función reset.", codeSnippet: "// Options API store\nexport const useSessionStore = defineStore('session', {\n  [INPUT_1]: () => ({ token: null, user: null }),\n  actions: {\n    logout() {\n      this.[INPUT_2]();\n    }\n  }\n});", inputs: { INPUT_1: "state", INPUT_2: "$reset" }, completeCode: "state: () => ({ token: null, user: null }),\nlogout() { this.$reset(); }" },
  { id: 8, title: "Composición entre Stores", stars: 4, category: "COMPOSITION", description: "Un store puede usar otro store internamente para componer lógica compleja.", objective: "Stores que dependen de otros stores", tags: ["composición", "useOtherStore", "DI"], fileName: "useOrderStore.ts", completed: false, explanationText: "Pinia permite que un store llame a otro store dentro de sus actions/getters, similar a inyectar servicios en .NET.", codeSnippet: "export const useOrderStore = defineStore('orders', () => {\n  const cartStore = [INPUT_1]();\n  const authStore = [INPUT_2]();\n  \n  const placeOrder = async () => {\n    if (!authStore.[INPUT_3]) throw new Error('No auth');\n    await api.post('/orders', { items: cartStore.[INPUT_4] });\n  };\n  return { placeOrder };\n});", inputs: { INPUT_1: "useCartStore", INPUT_2: "useAuthStore", INPUT_3: "isLoggedIn", INPUT_4: "items" }, completeCode: "const cartStore = useCartStore();\nconst authStore = useAuthStore();" }
];

// ─── FIREBASE (10 EJERCICIOS) ───────────────────────────────────────────────
const FIREBASE_EXERCISES = [
  { id: 1, title: "Inicializar Firebase en Vue", stars: 1, category: "SETUP", description: "Configura la instancia de Firebase con initializeApp usando tu objeto de configuración.", objective: "initializeApp() y configuración", tags: ["initializeApp", "config", "Firebase"], fileName: "firebase.ts", completed: false, explanationText: "initializeApp recibe un objeto de configuración del proyecto Firebase y devuelve la instancia de la app para usar los demás servicios.", codeSnippet: "import { [INPUT_1] } from 'firebase/app';\n\nconst firebaseConfig = {\n  apiKey: 'AIza...',\n  authDomain: 'myapp.firebaseapp.com',\n  projectId: 'myapp'\n};\n\nconst app = [INPUT_2](firebaseConfig);\nexport default [INPUT_3];", inputs: { INPUT_1: "initializeApp", INPUT_2: "initializeApp", INPUT_3: "app" }, completeCode: "import { initializeApp } from 'firebase/app';\nconst app = initializeApp(firebaseConfig);" },
  { id: 2, title: "Auth: Registro con Email/Password", stars: 2, category: "AUTH", description: "Registra un nuevo usuario usando createUserWithEmailAndPassword de Firebase Auth.", objective: "Crear usuarios con Firebase Auth", tags: ["createUser", "Auth", "email"], fileName: "register.ts", completed: false, explanationText: "createUserWithEmailAndPassword crea un usuario en Firebase Auth y devuelve un UserCredential con el uid único.", codeSnippet: "import { getAuth, [INPUT_1] } from 'firebase/auth';\n\nconst auth = [INPUT_2]();\n\nconst register = async (email, password) => {\n  const cred = await [INPUT_3](auth, email, [INPUT_4]);\n  return cred.user;\n};", inputs: { INPUT_1: "createUserWithEmailAndPassword", INPUT_2: "getAuth", INPUT_3: "createUserWithEmailAndPassword", INPUT_4: "password" }, completeCode: "const cred = await createUserWithEmailAndPassword(auth, email, password);" },
  { id: 3, title: "Auth: Login con Email/Password", stars: 2, category: "AUTH", description: "Autentica un usuario existente usando signInWithEmailAndPassword.", objective: "Iniciar sesión con Firebase Auth", tags: ["signIn", "Auth", "login"], fileName: "login.ts", completed: false, explanationText: "signInWithEmailAndPassword valida credenciales y establece la sesión del usuario. onAuthStateChanged detecta cambios de estado.", codeSnippet: "import { getAuth, [INPUT_1] } from 'firebase/auth';\n\nconst auth = getAuth();\n\nconst login = async (email, pass) => {\n  const cred = await [INPUT_2](auth, [INPUT_3], pass);\n  console.log('UID:', cred.user.[INPUT_4]);\n};", inputs: { INPUT_1: "signInWithEmailAndPassword", INPUT_2: "signInWithEmailAndPassword", INPUT_3: "email", INPUT_4: "uid" }, completeCode: "const cred = await signInWithEmailAndPassword(auth, email, pass);" },
  { id: 4, title: "Firestore: Leer Colección con getDocs", stars: 2, category: "FIRESTORE", description: "Obtén todos los documentos de una colección Firestore usando getDocs.", objective: "Consultar colecciones con getDocs", tags: ["getDocs", "collection", "Firestore"], fileName: "getUsers.ts", completed: false, explanationText: "getDocs retorna un QuerySnapshot. Cada doc tiene .id y .data() para acceder a los campos del documento.", codeSnippet: "import { getFirestore, [INPUT_1], [INPUT_2] } from 'firebase/firestore';\n\nconst db = getFirestore();\nconst snapshot = await getDocs([INPUT_3](db, 'users'));\n\nsnapshot.forEach(doc => {\n  console.log(doc.id, doc.[INPUT_4]());\n});", inputs: { INPUT_1: "collection", INPUT_2: "getDocs", INPUT_3: "collection", INPUT_4: "data" }, completeCode: "const snapshot = await getDocs(collection(db, 'users'));\nsnapshot.forEach(doc => console.log(doc.data()));" },
  { id: 5, title: "Firestore: Agregar Documento con addDoc", stars: 2, category: "FIRESTORE", description: "Inserta un nuevo documento a una colección Firestore con un ID auto-generado.", objective: "Inserción con addDoc", tags: ["addDoc", "collection", "insert"], fileName: "addOrder.ts", completed: false, explanationText: "addDoc genera un ID único automáticamente. Para IDs personalizados usa setDoc con doc(db, 'colección', 'miId').", codeSnippet: "import { getFirestore, collection, [INPUT_1] } from 'firebase/firestore';\n\nconst db = getFirestore();\nconst docRef = await [INPUT_2]([INPUT_3](db, 'orders'), {\n  product: 'Laptop',\n  total: 1500,\n  createdAt: new Date()\n});\nconsole.log('ID:', docRef.[INPUT_4]);", inputs: { INPUT_1: "addDoc", INPUT_2: "addDoc", INPUT_3: "collection", INPUT_4: "id" }, completeCode: "const docRef = await addDoc(collection(db, 'orders'), { product: 'Laptop', total: 1500 });" },
  { id: 6, title: "Firestore: Consultas con where", stars: 3, category: "FIRESTORE", description: "Filtra documentos usando query() y where() para obtener solo los activos.", objective: "Filtrado con where()", tags: ["query", "where", "filter"], fileName: "activeUsers.ts", completed: false, explanationText: "query() construye una consulta compuesta. where() acepta campo, operador y valor para filtrar documentos del lado del servidor.", codeSnippet: "import { collection, [INPUT_1], [INPUT_2], getDocs } from 'firebase/firestore';\n\nconst q = [INPUT_3](\n  collection(db, 'users'),\n  where('active', '[INPUT_4]', true)\n);\nconst snapshot = await getDocs(q);", inputs: { INPUT_1: "query", INPUT_2: "where", INPUT_3: "query", INPUT_4: "==" }, completeCode: "const q = query(collection(db, 'users'), where('active', '==', true));" },
  { id: 7, title: "Firestore: Listener en Tiempo Real", stars: 3, category: "REALTIME", description: "Escucha cambios en tiempo real de una colección usando onSnapshot.", objective: "Suscripción reactiva con onSnapshot", tags: ["onSnapshot", "realtime", "listener"], fileName: "liveChat.ts", completed: false, explanationText: "onSnapshot establece un listener que se dispara cada vez que los datos cambian en Firestore, ideal para chats y dashboards.", codeSnippet: "import { collection, [INPUT_1] } from 'firebase/firestore';\n\nconst unsubscribe = [INPUT_2](\n  collection(db, 'messages'),\n  (snapshot) => {\n    const msgs = snapshot.[INPUT_3].map(doc => ({\n      id: doc.id,\n      ...doc.[INPUT_4]()\n    }));\n  }\n);", inputs: { INPUT_1: "onSnapshot", INPUT_2: "onSnapshot", INPUT_3: "docs", INPUT_4: "data" }, completeCode: "const unsubscribe = onSnapshot(collection(db, 'messages'), (snapshot) => {\n  const msgs = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));\n});" },
  { id: 8, title: "Security Rules: Autenticación Requerida", stars: 3, category: "RULES", description: "Escribe reglas de seguridad que solo permitan lectura/escritura a usuarios autenticados.", objective: "Reglas de seguridad de Firestore", tags: ["rules", "request.auth", "security"], fileName: "firestore.rules", completed: false, explanationText: "request.auth es null para usuarios no autenticados. Las reglas se evalúan en el servidor, no en el cliente.", codeSnippet: "rules_version = '2';\nservice cloud.firestore {\n  match /databases/{database}/documents {\n    match /orders/{orderId} {\n      allow read, write: if [INPUT_1].[INPUT_2] != [INPUT_3];\n    }\n  }\n}", inputs: { INPUT_1: "request", INPUT_2: "auth", INPUT_3: "null" }, completeCode: "allow read, write: if request.auth != null;" },
  { id: 9, title: "Cloud Functions: Trigger onCreate", stars: 4, category: "FUNCTIONS", description: "Crea una Cloud Function que se ejecute automáticamente al crear un nuevo documento.", objective: "Triggers de Firestore con Cloud Functions", tags: ["functions", "onCreate", "trigger"], fileName: "index.ts", completed: false, explanationText: "Los triggers de Firestore ejecutan código serverless automáticamente cuando ocurren cambios en la base de datos.", codeSnippet: "import { onDocumentCreated } from 'firebase-functions/v2/firestore';\n\nexport const onNewOrder = [INPUT_1](\n  'orders/{orderId}',\n  (event) => {\n    const data = event.[INPUT_2].[INPUT_3]();\n    console.log('Nuevo pedido:', data);\n    return event.data.ref.[INPUT_4]({ processed: true });\n  }\n);", inputs: { INPUT_1: "onDocumentCreated", INPUT_2: "data", INPUT_3: "data", INPUT_4: "update" }, completeCode: "export const onNewOrder = onDocumentCreated('orders/{orderId}', (event) => {\n  const data = event.data.data();\n  return event.data.ref.update({ processed: true });\n});" },
  { id: 10, title: "Firebase App Check", stars: 4, category: "SECURITY", description: "Protege tu backend de Firebase contra abuso verificando que las solicitudes provienen de tu app legítima.", objective: "Protección con App Check", tags: ["AppCheck", "reCAPTCHA", "protección"], fileName: "appcheck.ts", completed: false, explanationText: "App Check usa un proveedor de atestación (reCAPTCHA Enterprise) para verificar que las solicitudes vienen de instancias legítimas de tu app.", codeSnippet: "import { [INPUT_1], ReCaptchaEnterpriseProvider } from 'firebase/app-check';\n\nconst appCheck = [INPUT_2](app, {\n  provider: new [INPUT_3]('SITE_KEY'),\n  isTokenAutoRefreshEnabled: [INPUT_4]\n});", inputs: { INPUT_1: "initializeAppCheck", INPUT_2: "initializeAppCheck", INPUT_3: "ReCaptchaEnterpriseProvider", INPUT_4: "true" }, completeCode: "const appCheck = initializeAppCheck(app, {\n  provider: new ReCaptchaEnterpriseProvider('SITE_KEY'),\n  isTokenAutoRefreshEnabled: true\n});" }
];

// ─── TYPESCRIPT CORE (10 EJERCICIOS) ────────────────────────────────────────
const TYPESCRIPT_EXERCISES = [
  { id: 1, title: "Tipos Primitivos", stars: 1, category: "BASICS", description: "Asigna tipos estrictos (number, string, boolean) a las variables.", objective: "Tipado de variables", tags: ["string", "number", "boolean"], fileName: "variables.ts", completed: false, explanationText: "TypeScript previene errores en runtime al forzar tipos en tiempo de compilación.", codeSnippet: "let edad: [INPUT_1] = 28;\nlet nombre: [INPUT_2] = 'Iram';\nlet activo: [INPUT_3] = true;", inputs: { INPUT_1: "number", INPUT_2: "string", INPUT_3: "boolean" }, completeCode: "let edad: number = 28;\nlet nombre: string = 'Iram';\nlet activo: boolean = true;" },
  { id: 2, title: "Interfaces y Propiedades Opcionales", stars: 2, category: "INTERFACES", description: "Define una interfaz con campos obligatorios y opcionales usando '?'.", objective: "Contratos con interface", tags: ["interface", "?", "contrato"], fileName: "user.interface.ts", completed: false, explanationText: "Las interfaces son contratos. '?' indica propiedad opcional, similar a nullables en C#.", codeSnippet: "interface Usuario {\n  id: [INPUT_1];\n  nombre: [INPUT_2];\n  celular[INPUT_3]: string;\n}", inputs: { INPUT_1: "number", INPUT_2: "string", INPUT_3: "?" }, completeCode: "interface Usuario { id: number; nombre: string; celular?: string; }" },
  { id: 3, title: "Type Aliases y Uniones Literales", stars: 2, category: "TYPES", description: "Crea un tipo con valores literales restringidos usando union types.", objective: "Union types literales", tags: ["type", "|", "literal"], fileName: "roles.ts", completed: false, explanationText: "Los Type Aliases definen formas o uniones de valores fijos, actuando como enums restrictivos.", codeSnippet: "type Rol = '[INPUT_1]' [INPUT_2] 'user';\nlet miRol: [INPUT_3] = 'admin';", inputs: { INPUT_1: "admin", INPUT_2: "|", INPUT_3: "Rol" }, completeCode: "type Rol = 'admin' | 'user';" },
  { id: 4, title: "Método .map() Tipado", stars: 2, category: "ARRAYS", description: "Transforma un arreglo tipado extrayendo solo los emails.", objective: ".map() con TypeScript", tags: ["map", "transform"], fileName: "map.ts", completed: false, explanationText: ".map() crea un nuevo arreglo con los resultados de una función callback aplicada a cada elemento.", codeSnippet: "interface Emp { nombre: string; email: string; }\nconst emps: Emp[] = [{ nombre: 'Iram', email: 'i@t.com' }];\nconst emails = emps.[INPUT_1](e => e.[INPUT_2]);", inputs: { INPUT_1: "map", INPUT_2: "email" }, completeCode: "const emails = emps.map(e => e.email);" },
  { id: 5, title: "Método .filter() Tipado", stars: 2, category: "ARRAYS", description: "Filtra elementos de un arreglo tipado por condición.", objective: ".filter() condicional", tags: ["filter", "predicate"], fileName: "filter.ts", completed: false, explanationText: ".filter() retorna un nuevo arreglo con solo los elementos que cumplen la condición del callback.", codeSnippet: "interface Order { id: number; status: string; }\nconst orders: Order[] = [{ id: 1, status: 'pending' }];\nconst pending = orders.[INPUT_1](o => o.[INPUT_2] === '[INPUT_3]');", inputs: { INPUT_1: "filter", INPUT_2: "status", INPUT_3: "pending" }, completeCode: "const pending = orders.filter(o => o.status === 'pending');" },
  { id: 6, title: "Método .reduce() Acumulador", stars: 3, category: "ARRAYS", description: "Suma precios de un carrito usando reduce con acumulador.", objective: "Acumulador con .reduce()", tags: ["reduce", "acumulador"], fileName: "reduce.ts", completed: false, explanationText: ".reduce() procesa cada elemento para acumular un valor final de salida.", codeSnippet: "interface Item { price: number; }\nconst cart: Item[] = [{ price: 100 }, { price: 50 }];\nconst total = cart.[INPUT_1]((acc, item) => acc + item.[INPUT_2], [INPUT_3]);", inputs: { INPUT_1: "reduce", INPUT_2: "price", INPUT_3: "0" }, completeCode: "const total = cart.reduce((acc, item) => acc + item.price, 0);" },
  { id: 7, title: "Funciones con Tipos de Retorno", stars: 2, category: "FUNCTIONS", description: "Tipa los parámetros y el retorno de una función.", objective: "Firmas tipadas", tags: ["function", "return type"], fileName: "suma.ts", completed: false, explanationText: "TS exige tipar parámetros y retorno para evitar fugas de tipo any.", codeSnippet: "function sumar(a: [INPUT_1], b: [INPUT_2]): [INPUT_3] {\n  return a + b;\n}", inputs: { INPUT_1: "number", INPUT_2: "number", INPUT_3: "number" }, completeCode: "function sumar(a: number, b: number): number { return a + b; }" },
  { id: 8, title: "Generics: Reutilización de Tipos", stars: 4, category: "GENERICS", description: "Crea una función genérica que reciba y devuelva cualquier tipo T.", objective: "Genéricos en TypeScript", tags: ["generics", "<T>"], fileName: "generic.ts", completed: false, explanationText: "Los genéricos crean plantillas de código reutilizables que adaptan su tipo según el uso, como en C#.", codeSnippet: "function identity<[INPUT_1]>(val: [INPUT_2]): [INPUT_3] {\n  return val;\n}", inputs: { INPUT_1: "T", INPUT_2: "T", INPUT_3: "T" }, completeCode: "function identity<T>(val: T): T { return val; }" },
  { id: 9, title: "Utility Types: Pick y Omit", stars: 4, category: "UTILITIES", description: "Usa Pick para crear un subtipo seleccionando solo ciertos campos.", objective: "Pick<T, K> utility type", tags: ["Pick", "Omit", "Utility"], fileName: "pick.ts", completed: false, explanationText: "Pick<T, K> construye un tipo seleccionando un subconjunto de llaves de T.", codeSnippet: "interface Product { id: number; name: string; price: number; }\ntype Summary = [INPUT_1]<Product, '[INPUT_2]' | '[INPUT_3]'>;", inputs: { INPUT_1: "Pick", INPUT_2: "id", INPUT_3: "name" }, completeCode: "type Summary = Pick<Product, 'id' | 'name'>;" },
  { id: 10, title: "Enums y Discriminated Unions", stars: 3, category: "PATTERNS", description: "Usa enums y discriminated unions para modelar estados de forma segura.", objective: "Enums + union types", tags: ["enum", "discriminated", "pattern"], fileName: "status.ts", completed: false, explanationText: "Los discriminated unions usan un campo literal común para que TS infiera el tipo correcto en cada rama del switch/if.", codeSnippet: "enum Status {\n  Loading = '[INPUT_1]',\n  Success = 'success',\n  Error = 'error'\n}\n\ntype Result =\n  | { status: Status.Success; data: string[] }\n  | { status: Status.[INPUT_2]; message: string };\n\nfunction handle(r: Result) {\n  if (r.status === Status.[INPUT_3]) {\n    console.log(r.[INPUT_4]);\n  }\n}", inputs: { INPUT_1: "loading", INPUT_2: "Error", INPUT_3: "Error", INPUT_4: "message" }, completeCode: "enum Status { Loading = 'loading', Success = 'success', Error = 'error' }" }
];

// ─── SQL SERVER (10 EJERCICIOS) ─────────────────────────────────────────────
const SQL_EXERCISES = [
  { id: 1, title: "INNER JOIN", stars: 2, category: "JOINS", description: "Obtén empleados con departamento asignado.", objective: "JOIN asociativo simple", tags: ["INNER JOIN"], fileName: "Q1.sql", completed: false, explanationText: "INNER JOIN solo devuelve filas que cumplen la condición en ambas tablas.", codeSnippet: "SELECT e.Nombre, d.NombreDepto\nFROM Empleados e\n[INPUT_1] JOIN Departamentos d\n  [INPUT_2] e.DeptoID [INPUT_3] d.DeptoID;", inputs: { INPUT_1: "INNER", INPUT_2: "ON", INPUT_3: "=" }, completeCode: "SELECT e.Nombre, d.NombreDepto FROM Empleados e INNER JOIN Departamentos d ON e.DeptoID = d.DeptoID;" },
  { id: 2, title: "LEFT JOIN", stars: 2, category: "JOINS", description: "Obtén TODOS los empleados, NULL si no tienen departamento.", objective: "Preservación izquierda", tags: ["LEFT JOIN", "NULL"], fileName: "Q2.sql", completed: false, explanationText: "LEFT JOIN garantiza todas las filas de la tabla izquierda.", codeSnippet: "SELECT e.Nombre, d.NombreDepto\nFROM Empleados e\n[INPUT_1] JOIN Departamentos d\n  [INPUT_2] e.DeptoID [INPUT_3] d.DeptoID;", inputs: { INPUT_1: "LEFT", INPUT_2: "ON", INPUT_3: "=" }, completeCode: "LEFT JOIN ... ON e.DeptoID = d.DeptoID;" },
  { id: 3, title: "SELF JOIN Jerárquico", stars: 4, category: "JOINS", description: "Relaciona empleados con sus jefes en la misma tabla.", objective: "Relación reflexiva", tags: ["SELF JOIN", "Aliases"], fileName: "Q3.sql", completed: false, explanationText: "SELF JOIN une una tabla consigo misma usando aliases distintos para resolver jerarquías.", codeSnippet: "SELECT e.Nombre AS Empleado, [INPUT_1].Nombre AS Jefe\nFROM Empleados e\nINNER JOIN Empleados [INPUT_2]\n  ON e.JefeID = [INPUT_3].EmpleadoID;", inputs: { INPUT_1: "j", INPUT_2: "j", INPUT_3: "j" }, completeCode: "SELECT e.Nombre AS Empleado, j.Nombre AS Jefe FROM Empleados e INNER JOIN Empleados j ON e.JefeID = j.EmpleadoID;" },
  { id: 4, title: "Función Escalar", stars: 3, category: "FUNCIONES", description: "Crea una función que calcule descuentos sobre un precio.", objective: "RETURNS escalar", tags: ["Scalar", "FUNCTION"], fileName: "Fn1.sql", completed: false, explanationText: "Las funciones escalares devuelven un único valor, ideal para cálculos reutilizables.", codeSnippet: "CREATE FUNCTION dbo.fn_Descuento (@Precio DECIMAL(18,2), @Desc INT)\nRETURNS [INPUT_1](18,2)\nAS\nBEGIN\n  RETURN @Precio - (@Precio * (@Desc / [INPUT_2]));\n[INPUT_3];", inputs: { INPUT_1: "DECIMAL", INPUT_2: "100.0", INPUT_3: "END" }, completeCode: "RETURNS DECIMAL(18,2) AS BEGIN RETURN @Precio - (@Precio * (@Desc / 100.0)); END;" },
  { id: 5, title: "Table-Valued Function", stars: 4, category: "FUNCIONES", description: "Crea una TVF que reciba un año y devuelva empleados contratados ese año.", objective: "RETURNS TABLE inline", tags: ["TVF", "Inline"], fileName: "Fn2.sql", completed: false, explanationText: "Las TVF inline se optimizan en el plan de ejecución como vistas parametrizadas.", codeSnippet: "CREATE FUNCTION dbo.fn_EmpAnio (@Anio INT)\nRETURNS [INPUT_1]\nAS\nRETURN (\n  SELECT EmpleadoID, Nombre FROM Empleados\n  WHERE [INPUT_2](FechaContratacion) = @Anio\n);", inputs: { INPUT_1: "TABLE", INPUT_2: "YEAR" }, completeCode: "RETURNS TABLE AS RETURN (SELECT ... WHERE YEAR(FechaContratacion) = @Anio);" },
  { id: 6, title: "Índice Non-Clustered", stars: 3, category: "INDEXES", description: "Crea un índice para acelerar búsquedas por Email.", objective: "CREATE INDEX", tags: ["INDEX", "B-Tree"], fileName: "Idx1.sql", completed: false, explanationText: "Un índice no agrupado crea una estructura B-Tree secundaria sin alterar el orden físico.", codeSnippet: "CREATE [INPUT_1] INDEX IX_Clientes_Email\n[INPUT_2] Clientes ([INPUT_3]);", inputs: { INPUT_1: "NONCLUSTERED", INPUT_2: "ON", INPUT_3: "Email" }, completeCode: "CREATE NONCLUSTERED INDEX IX_Clientes_Email ON Clientes (Email);" },
  { id: 7, title: "Vista de Seguridad", stars: 3, category: "VISTAS", description: "Crea una vista que exponga solo campos no sensibles.", objective: "CREATE VIEW", tags: ["VIEW", "Seguridad"], fileName: "V1.sql", completed: false, explanationText: "Las vistas encapsulan lógica y proveen seguridad ocultando columnas sensibles.", codeSnippet: "CREATE [INPUT_1] dbo.v_Directorio\n[INPUT_2]\nSELECT Nombre, Email FROM Empleados WHERE Activo = [INPUT_3];", inputs: { INPUT_1: "VIEW", INPUT_2: "AS", INPUT_3: "1" }, completeCode: "CREATE VIEW dbo.v_Directorio AS SELECT Nombre, Email FROM Empleados WHERE Activo = 1;" },
  { id: 8, title: "Trigger AFTER UPDATE", stars: 5, category: "TRIGGERS", description: "Audita cambios de salario usando inserted y deleted.", objective: "Tablas virtuales inserted/deleted", tags: ["TRIGGER", "Auditoría"], fileName: "Trg1.sql", completed: false, explanationText: "'deleted' tiene valores antiguos, 'inserted' los nuevos. Comparar ambos permite auditar cambios.", codeSnippet: "CREATE TRIGGER trg_SalarioAudit\nON Empleados AFTER [INPUT_1]\nAS\nBEGIN\n  INSERT INTO Auditoria (EmpID, Antes, Despues)\n  SELECT i.EmpID, d.Salario, i.Salario\n  FROM [INPUT_2] i\n  INNER JOIN [INPUT_3] d ON i.EmpID = d.EmpID;\nEND;", inputs: { INPUT_1: "UPDATE", INPUT_2: "inserted", INPUT_3: "deleted" }, completeCode: "AFTER UPDATE ... FROM inserted i INNER JOIN deleted d ON i.EmpID = d.EmpID;" },
  { id: 9, title: "Row-Level Security", stars: 5, category: "SEGURIDAD", description: "Implementa políticas RLS para filtrar filas por usuario.", objective: "SECURITY POLICY", tags: ["RLS", "POLICY"], fileName: "RLS.sql", completed: false, explanationText: "RLS intercepta consultas y aplica un filtro dinámico transparente basado en el usuario.", codeSnippet: "CREATE FUNCTION dbo.fn_Filtro (@User SYSNAME)\nRETURNS TABLE WITH SCHEMABINDING AS\nRETURN SELECT 1 AS OK WHERE @User = USER_NAME();\n\nCREATE [INPUT_1] [INPUT_2] p_Filtro\nADD FILTER PREDICATE dbo.fn_Filtro(Usuario) ON dbo.Empleados;", inputs: { INPUT_1: "SECURITY", INPUT_2: "POLICY" }, completeCode: "CREATE SECURITY POLICY p_Filtro ADD FILTER PREDICATE dbo.fn_Filtro(Usuario) ON dbo.Empleados;" },
  { id: 10, title: "Dynamic Data Masking", stars: 4, category: "SEGURIDAD", description: "Enmascara datos sensibles como tarjetas de crédito.", objective: "MASKED WITH FUNCTION", tags: ["DDM", "MASKED"], fileName: "DDM.sql", completed: false, explanationText: "DDM oculta datos confidenciales en runtime a usuarios sin privilegio UNMASK.", codeSnippet: "ALTER TABLE Clientes\nALTER COLUMN Tarjeta ADD [INPUT_1] WITH (FUNCTION = '[INPUT_2](0, \"XXXX-\", 4)');", inputs: { INPUT_1: "MASKED", INPUT_2: "partial" }, completeCode: "ALTER COLUMN Tarjeta ADD MASKED WITH (FUNCTION = 'partial(0, \"XXXX-\", 4)');" }
];

// ─── VITEST TESTING (8 EJERCICIOS) ──────────────────────────────────────────
const VITEST_EXERCISES = [
  { id: 1, title: "Aserciones toBe y toEqual", stars: 1, category: "ASSERTIONS", description: "Usa toBe para igualdad referencial y toEqual para comparación profunda.", objective: "Aserciones básicas", tags: ["toBe", "toEqual", "expect"], fileName: "math.test.ts", completed: false, explanationText: "toBe usa === (referencial), toEqual compara estructura profunda en objetos/arrays.", codeSnippet: "import { describe, test, expect } from 'vitest';\n\ndescribe('Math', () => {\n  test('values', () => {\n    expect(2 + 2).[INPUT_1](4);\n    expect({ id: 1 }).[INPUT_2]({ id: 1 });\n  });\n});", inputs: { INPUT_1: "toBe", INPUT_2: "toEqual" }, completeCode: "expect(2 + 2).toBe(4);\nexpect({ id: 1 }).toEqual({ id: 1 });" },
  { id: 2, title: "Tests Asíncronos", stars: 2, category: "ASYNC", description: "Prueba resolución de promesas con resolves.", objective: "async/await en tests", tags: ["async", "resolves", "rejects"], fileName: "async.test.ts", completed: false, explanationText: "Vitest requiere 'resolves'/'rejects' con await para esperar el ciclo de vida de la promesa.", codeSnippet: "test('resolves', [INPUT_1] () => {\n  const p = Promise.resolve('OK');\n  await expect(p).[INPUT_2].toBe('OK');\n});", inputs: { INPUT_1: "async", INPUT_2: "resolves" }, completeCode: "test('resolves', async () => { await expect(p).resolves.toBe('OK'); });" },
  { id: 3, title: "Mocks con vi.fn()", stars: 3, category: "MOCKS", description: "Crea un espía y verifica sus llamadas.", objective: "vi.fn() y toHaveBeenCalledWith", tags: ["vi.fn", "spy", "mock"], fileName: "callback.test.ts", completed: false, explanationText: "vi.fn() crea una función simulada que registra sus llamadas para posterior verificación.", codeSnippet: "import { vi, test, expect } from 'vitest';\n\ntest('spy', () => {\n  const mock = vi.[INPUT_1]();\n  mock('data');\n  expect(mock).[INPUT_2]('data');\n});", inputs: { INPUT_1: "fn", INPUT_2: "toHaveBeenCalledWith" }, completeCode: "const mock = vi.fn();\nmock('data');\nexpect(mock).toHaveBeenCalledWith('data');" },
  { id: 4, title: "Vue Test Utils: mount + trigger", stars: 4, category: "COMPONENTS", description: "Monta un componente Vue y simula un click.", objective: "Component testing", tags: ["mount", "trigger", "VTU"], fileName: "Counter.test.ts", completed: false, explanationText: "mount() renderiza el componente en un DOM sintético. trigger() simula eventos del usuario.", codeSnippet: "import { [INPUT_1] } from '@vue/test-utils';\nimport Counter from './Counter.vue';\n\ntest('click', async () => {\n  const w = [INPUT_2](Counter);\n  await w.find('button').[INPUT_3]('click');\n  expect(w.text()).toContain('1');\n});", inputs: { INPUT_1: "mount", INPUT_2: "mount", INPUT_3: "trigger" }, completeCode: "const w = mount(Counter);\nawait w.find('button').trigger('click');" },
  { id: 5, title: "beforeEach / afterEach", stars: 3, category: "LIFECYCLE", description: "Configura hooks de limpieza para evitar contaminación entre tests.", objective: "Setup y teardown", tags: ["beforeEach", "afterEach", "cleanup"], fileName: "lifecycle.test.ts", completed: false, explanationText: "Los hooks de limpieza evitan que estado residual de tests previos contamine tests posteriores.", codeSnippet: "import { [INPUT_1], [INPUT_2], vi } from 'vitest';\n\n[INPUT_3](() => {\n  // setup\n});\n\n[INPUT_4](() => {\n  vi.clearAllMocks();\n});", inputs: { INPUT_1: "beforeEach", INPUT_2: "afterEach", INPUT_3: "beforeEach", INPUT_4: "afterEach" }, completeCode: "beforeEach(() => { /* setup */ });\nafterEach(() => { vi.clearAllMocks(); });" },
  { id: 6, title: "vi.mock(): Mockear Módulos", stars: 4, category: "MOCKS", description: "Mockea un módulo completo para aislar la unidad bajo prueba.", objective: "Module mocking", tags: ["vi.mock", "módulo", "aislamiento"], fileName: "service.test.ts", completed: false, explanationText: "vi.mock() reemplaza las importaciones de un módulo completo con implementaciones simuladas.", codeSnippet: "import { vi, test, expect } from 'vitest';\nimport { fetchUsers } from './api';\n\nvi.[INPUT_1]('./api', () => ({\n  fetchUsers: vi.fn().[INPUT_2]([{ id: 1 }])\n}));\n\ntest('mocked', async () => {\n  const users = await [INPUT_3]();\n  expect(users).toHaveLength([INPUT_4]);\n});", inputs: { INPUT_1: "mock", INPUT_2: "mockResolvedValue", INPUT_3: "fetchUsers", INPUT_4: "1" }, completeCode: "vi.mock('./api', () => ({ fetchUsers: vi.fn().mockResolvedValue([{ id: 1 }]) }));" },
  { id: 7, title: "Testing de Stores (Pinia)", stars: 4, category: "STORES", description: "Prueba un store de Pinia usando createTestingPinia.", objective: "Testear actions y state de Pinia", tags: ["Pinia", "createTestingPinia", "store"], fileName: "store.test.ts", completed: false, explanationText: "createTestingPinia crea una instancia de Pinia aislada con actions mockeadas por defecto.", codeSnippet: "import { setActivePinia, [INPUT_1] } from 'pinia';\nimport { useCartStore } from './stores/cart';\n\nbeforeEach(() => {\n  setActivePinia([INPUT_2]());\n});\n\ntest('adds item', () => {\n  const store = [INPUT_3]();\n  store.addItem({ id: 1, price: 100 });\n  expect(store.items).toHaveLength([INPUT_4]);\n});", inputs: { INPUT_1: "createPinia", INPUT_2: "createPinia", INPUT_3: "useCartStore", INPUT_4: "1" }, completeCode: "setActivePinia(createPinia());\nconst store = useCartStore();" },
  { id: 8, title: "Snapshot Testing", stars: 3, category: "SNAPSHOTS", description: "Verifica que la salida renderizada no cambie inesperadamente con snapshots.", objective: "toMatchSnapshot()", tags: ["snapshot", "regression", "UI"], fileName: "snapshot.test.ts", completed: false, explanationText: "Los snapshots capturan una 'foto' del output. Si cambia, el test falla y debes confirmar si el cambio es intencional.", codeSnippet: "import { mount } from '@vue/test-utils';\nimport Card from './Card.vue';\n\ntest('renders correctly', () => {\n  const wrapper = [INPUT_1](Card, { props: { title: 'Test' } });\n  expect(wrapper.[INPUT_2]()).[INPUT_3]();\n});", inputs: { INPUT_1: "mount", INPUT_2: "html", INPUT_3: "toMatchSnapshot" }, completeCode: "expect(wrapper.html()).toMatchSnapshot();" }
];

// ─── SECURITY: OAuth2, JWT, CORS, HTTPS (10 EJERCICIOS) ────────────────────
const SECURITY_EXERCISES = [
  { id: 1, title: "Anatomía de un JWT", stars: 2, category: "JWT", description: "Identifica las 3 partes de un JSON Web Token.", objective: "Header.Payload.Signature", tags: ["JWT", "Base64Url"], fileName: "jwt.txt", completed: false, explanationText: "JWT tiene 3 secciones codificadas en Base64Url separadas por puntos. La firma valida integridad.", codeSnippet: "JWT = [INPUT_1] + '.' + [INPUT_2] + '.' + [INPUT_3];", inputs: { INPUT_1: "Header", INPUT_2: "Payload", INPUT_3: "Signature" }, completeCode: "JWT = Header + '.' + Payload + '.' + Signature;" },
  { id: 2, title: "Algoritmo RS256 vs HS256", stars: 3, category: "JWT", description: "Selecciona el algoritmo asimétrico recomendado para microservicios.", objective: "RS256 con clave pública/privada", tags: ["RS256", "asimétrico"], fileName: "alg.cs", completed: false, explanationText: "RS256 usa clave privada para firmar y pública para verificar, ideal para arquitecturas distribuidas.", codeSnippet: "var descriptor = new SecurityTokenDescriptor {\n  SigningCredentials = new SigningCredentials(\n    new [INPUT_1](privateKey),\n    SecurityAlgorithms.[INPUT_2]\n  )\n};", inputs: { INPUT_1: "RsaSecurityKey", INPUT_2: "RsaSha256Signature" }, completeCode: "new RsaSecurityKey(privateKey), SecurityAlgorithms.RsaSha256Signature" },
  { id: 3, title: "Refresh Tokens en HttpOnly Cookies", stars: 4, category: "OAUTH2", description: "Almacena refresh tokens de forma segura en cookies HttpOnly.", objective: "Gestión segura de sesiones", tags: ["HttpOnly", "Secure", "SameSite"], fileName: "refresh.cs", completed: false, explanationText: "HttpOnly previene acceso desde JavaScript (XSS). SameSite=Strict previene CSRF.", codeSnippet: "Response.Cookies.Append(\"refresh\", token, new CookieOptions {\n  [INPUT_1] = true,\n  Secure = true,\n  [INPUT_2] = SameSiteMode.[INPUT_3]\n});", inputs: { INPUT_1: "HttpOnly", INPUT_2: "SameSite", INPUT_3: "Strict" }, completeCode: "HttpOnly = true, Secure = true, SameSite = SameSiteMode.Strict" },
  { id: 4, title: "OAuth 2.0 + PKCE para SPAs", stars: 4, category: "OAUTH2", description: "Implementa Authorization Code Flow con PKCE para apps frontend.", objective: "PKCE sin client_secret", tags: ["PKCE", "S256", "code_challenge"], fileName: "pkce.js", completed: false, explanationText: "PKCE reemplaza el client_secret con un code_verifier/code_challenge para clientes públicos.", codeSnippet: "authRequest.send({\n  response_type: 'code',\n  code_challenge: [INPUT_1],\n  code_challenge_method: '[INPUT_2]'\n});", inputs: { INPUT_1: "codeChallenge", INPUT_2: "S256" }, completeCode: "code_challenge: codeChallenge, code_challenge_method: 'S256'" },
  { id: 5, title: "Content Security Policy (CSP)", stars: 4, category: "HEADERS", description: "Configura CSP para prevenir XSS.", objective: "Headers de seguridad", tags: ["CSP", "XSS", "headers"], fileName: "csp.cs", completed: false, explanationText: "CSP le dice al navegador qué dominios pueden ejecutar scripts, previniendo inyección.", codeSnippet: "app.Use(async (ctx, next) => {\n  ctx.Response.Headers.Append(\n    \"[INPUT_1]\",\n    \"[INPUT_2] 'self';\"\n  );\n  await [INPUT_3]();\n});", inputs: { INPUT_1: "Content-Security-Policy", INPUT_2: "default-src", INPUT_3: "next" }, completeCode: "Content-Security-Policy: default-src 'self';" },
  { id: 6, title: "CORS: Configuración en .NET", stars: 3, category: "CORS", description: "Configura CORS en ASP.NET Core para permitir peticiones desde tu frontend.", objective: "AddCors y UseCors", tags: ["CORS", "AllowOrigins", ".NET"], fileName: "cors.cs", completed: false, explanationText: "CORS (Cross-Origin Resource Sharing) controla qué dominios externos pueden acceder a tu API.", codeSnippet: "builder.Services.AddCors(options => {\n  options.[INPUT_1](\"MiPolitica\", policy => {\n    policy.[INPUT_2](\"https://miapp.com\")\n          .AllowAnyHeader()\n          .[INPUT_3]();\n  });\n});", inputs: { INPUT_1: "AddPolicy", INPUT_2: "WithOrigins", INPUT_3: "AllowAnyMethod" }, completeCode: "AddPolicy > WithOrigins > AllowAnyHeader > AllowAnyMethod" },
  { id: 7, title: "HTTPS Redirect Middleware", stars: 2, category: "HTTPS", description: "Fuerza HTTPS en tu aplicación ASP.NET Core.", objective: "UseHttpsRedirection", tags: ["HTTPS", "redirect", "TLS"], fileName: "https.cs", completed: false, explanationText: "UseHttpsRedirection redirige automáticamente peticiones HTTP a HTTPS con un 307.", codeSnippet: "var app = builder.Build();\napp.[INPUT_1]();\napp.UseHsts();", inputs: { INPUT_1: "UseHttpsRedirection" }, completeCode: "app.UseHttpsRedirection();\napp.UseHsts();" },
  { id: 8, title: "Validación de JWT en Middleware", stars: 4, category: "AUTH", description: "Configura la validación automática de tokens JWT en el pipeline de .NET.", objective: "AddJwtBearer validation", tags: ["AddJwtBearer", "TokenValidation"], fileName: "auth.cs", completed: false, explanationText: "AddJwtBearer configura el middleware de autenticación para validar tokens JWT automáticamente en cada request.", codeSnippet: "builder.Services.AddAuthentication()\n  .[INPUT_1](options => {\n    options.TokenValidationParameters = new TokenValidationParameters {\n      ValidateIssuer = [INPUT_2],\n      ValidateAudience = true,\n      [INPUT_3] = new SymmetricSecurityKey(key)\n    };\n  });", inputs: { INPUT_1: "AddJwtBearer", INPUT_2: "true", INPUT_3: "IssuerSigningKey" }, completeCode: "AddJwtBearer with TokenValidationParameters" },
  { id: 9, title: "Firebase Security Rules Avanzadas", stars: 4, category: "FIREBASE", description: "Escribe reglas que solo permitan a usuarios modificar sus propios documentos.", objective: "Owner-only access rules", tags: ["rules", "resource.data", "uid"], fileName: "firestore.rules", completed: false, explanationText: "resource.data accede a los campos del documento existente. request.auth.uid es el ID del usuario autenticado.", codeSnippet: "match /users/{userId} {\n  allow read: if request.auth != null;\n  allow write: if request.[INPUT_1].[INPUT_2] == [INPUT_3];\n}", inputs: { INPUT_1: "auth", INPUT_2: "uid", INPUT_3: "userId" }, completeCode: "allow write: if request.auth.uid == userId;" },
  { id: 10, title: "Sanitización de Inputs (XSS Prevention)", stars: 3, category: "XSS", description: "Previene XSS escapando HTML antes de renderizarlo en el DOM.", objective: "Escape de caracteres peligrosos", tags: ["XSS", "sanitize", "escape"], fileName: "sanitize.ts", completed: false, explanationText: "Nunca insertes input del usuario como innerHTML sin sanitizar. Escapa <, >, &, \" y ' como mínimo.", codeSnippet: "function sanitize(input: string): string {\n  return input\n    .replace(/&/g, '&amp;')\n    .replace(/</g, '[INPUT_1]')\n    .replace(/>/g, '[INPUT_2]')\n    .replace(/\"/g, '[INPUT_3]');\n}", inputs: { INPUT_1: "&lt;", INPUT_2: "&gt;", INPUT_3: "&quot;" }, completeCode: "replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/\"/g, '&quot;')" }
];

// ─── AXIOS & FETCH API (15 EJERCICIOS) ──────────────────────────────────────
const API_EXERCISES = [
  { id: 1, title: "Fetch GET + .json()", stars: 2, category: "FETCH GET", description: "Fetch devuelve un stream; usa .json() para parsearlo.", objective: ".json() en Fetch", tags: ["fetch", "GET"], fileName: "get.js", completed: false, explanationText: "Fetch devuelve un Response. .json() lee y parsea el stream del body.", codeSnippet: "fetch('/api/users')\n  .then(res => res.[INPUT_1]())\n  .then(data => console.log([INPUT_2]));", inputs: { INPUT_1: "json", INPUT_2: "data" }, completeCode: "fetch('/api/users').then(res => res.json()).then(data => console.log(data));" },
  { id: 2, title: "Fetch: Verificar response.ok", stars: 3, category: "FETCH ERRORS", description: "Fetch NO rechaza ante errores HTTP. Verifica manualmente.", objective: "Error handling en Fetch", tags: ["response.ok", "throw"], fileName: "ok.js", completed: false, explanationText: "Fetch solo rechaza ante caídas de red. Errores HTTP se detectan con response.ok.", codeSnippet: "fetch('/api/data')\n  .then(res => {\n    if (!res.[INPUT_1]) [INPUT_2] new Error('Server error');\n    return res.json();\n  });", inputs: { INPUT_1: "ok", INPUT_2: "throw" }, completeCode: "if (!res.ok) throw new Error(...);" },
  { id: 3, title: "Axios GET: Propiedad data", stars: 2, category: "AXIOS GET", description: "Axios parsea JSON automáticamente en response.data.", objective: ".data de Axios", tags: ["axios", "data"], fileName: "axiosGet.js", completed: false, explanationText: "Axios simplifica el flujo encapsulando el payload en .data.", codeSnippet: "axios.get('/api/products')\n  .then(res => console.log(res.[INPUT_1]));", inputs: { INPUT_1: "data" }, completeCode: "console.log(res.data);" },
  { id: 4, title: "Fetch POST: Headers y Body", stars: 3, category: "FETCH POST", description: "Configura método, headers y body serializado.", objective: "POST con Fetch", tags: ["POST", "stringify"], fileName: "post.js", completed: false, explanationText: "En Fetch POST el body debe ir serializado y Content-Type especificado.", codeSnippet: "fetch('/api/orders', {\n  method: '[INPUT_1]',\n  headers: { 'Content-Type': '[INPUT_2]' },\n  body: JSON.[INPUT_3]({ id: 1 })\n});", inputs: { INPUT_1: "POST", INPUT_2: "application/json", INPUT_3: "stringify" }, completeCode: "method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(...);" },
  { id: 5, title: "Axios POST directo", stars: 2, category: "AXIOS POST", description: "Axios serializa automáticamente. Pasa el objeto directo.", objective: "POST simplificado", tags: ["axios.post"], fileName: "axiosPost.js", completed: false, explanationText: "Axios reduce el envío a URL + objeto. Headers se configuran automáticamente.", codeSnippet: "axios.[INPUT_1]('/api/clients', { name: 'Iram' });", inputs: { INPUT_1: "post" }, completeCode: "axios.post('/api/clients', { name: 'Iram' });" },
  { id: 6, title: "Manejo de Errores en Axios", stars: 3, category: "AXIOS ERRORS", description: "Axios rechaza en errores HTTP. Accede al detalle en catch.", objective: "error.response en Axios", tags: ["catch", "error.response"], fileName: "catch.js", completed: false, explanationText: "Axios expone la respuesta fallida en error.response con status y data.", codeSnippet: "axios.get('/api/secret')\n  .[INPUT_1](res => console.log(res))\n  .[INPUT_2](err => console.log(err.[INPUT_3].status));", inputs: { INPUT_1: "then", INPUT_2: "catch", INPUT_3: "response" }, completeCode: ".catch(err => console.log(err.response.status));" },
  { id: 7, title: "Headers de Authorization Bearer", stars: 3, category: "AUTH", description: "Inyecta el token JWT en los headers de la petición.", objective: "Bearer token en headers", tags: ["Authorization", "Bearer"], fileName: "bearer.js", completed: false, explanationText: "Los endpoints [Authorize] requieren el header Authorization: Bearer <token>.", codeSnippet: "axios.get('/api/sales', {\n  [INPUT_1]: { '[INPUT_2]': 'Bearer ' + token }\n});", inputs: { INPUT_1: "headers", INPUT_2: "Authorization" }, completeCode: "headers: { 'Authorization': 'Bearer ' + token }" },
  { id: 8, title: "Interceptors de Request", stars: 4, category: "INTERCEPTORS", description: "Automatiza inyección de tokens en todas las peticiones.", objective: "interceptors.request.use", tags: ["interceptors", "global"], fileName: "interceptor.js", completed: false, explanationText: "Los interceptores decoran peticiones antes de salir a la red, centralizando autenticación.", codeSnippet: "axios.[INPUT_1].[INPUT_2].use(config => {\n  config.headers.Authorization = 'Bearer ' + token;\n  return config;\n});", inputs: { INPUT_1: "interceptors", INPUT_2: "request" }, completeCode: "axios.interceptors.request.use(config => { ... return config; });" },
  { id: 9, title: "Promise.all: Peticiones Paralelas", stars: 3, category: "CONCURRENCY", description: "Ejecuta peticiones independientes en paralelo.", objective: "Paralelismo HTTP", tags: ["Promise.all", "parallel"], fileName: "parallel.js", completed: false, explanationText: "Promise.all dispara todas las promesas y espera a que todas se resuelvan.", codeSnippet: "Promise.[INPUT_1]([fetch('/api/a'), fetch('/api/b')])\n  .then(([r1, r2]) => {});", inputs: { INPUT_1: "all" }, completeCode: "Promise.all([...]).then(([r1, r2]) => {});" },
  { id: 10, title: "AbortController: Cancelar Peticiones", stars: 4, category: "ADVANCED", description: "Cancela peticiones en curso cuando el usuario sale de la vista.", objective: "AbortController + signal", tags: ["AbortController", "signal", "abort"], fileName: "abort.js", completed: false, explanationText: "AbortController permite cancelar la conexión de red con una señal.", codeSnippet: "const ctrl = new [INPUT_1]();\nfetch('/api/heavy', { [INPUT_2]: ctrl.signal });\nctrl.[INPUT_3]();", inputs: { INPUT_1: "AbortController", INPUT_2: "signal", INPUT_3: "abort" }, completeCode: "const ctrl = new AbortController();\nfetch(url, { signal: ctrl.signal });\nctrl.abort();" },
  { id: 11, title: "Axios Timeout", stars: 3, category: "CONFIG", description: "Define tiempo máximo de espera.", objective: "Propiedad timeout", tags: ["timeout", "config"], fileName: "timeout.js", completed: false, explanationText: "timeout en Axios define milisegundos máximos antes de abortar.", codeSnippet: "axios.get('/api/reports', { [INPUT_1]: 5000 });", inputs: { INPUT_1: "timeout" }, completeCode: "axios.get(url, { timeout: 5000 });" },
  { id: 12, title: "URLSearchParams en Fetch", stars: 3, category: "QUERY", description: "Construye query strings seguros con URLSearchParams.", objective: "URLSearchParams nativo", tags: ["URLSearchParams", "query"], fileName: "query.js", completed: false, explanationText: "URLSearchParams escapa caracteres especiales automáticamente.", codeSnippet: "const p = new [INPUT_1]();\np.[INPUT_2]('active', 'true');\nfetch('/api/users?' + p.toString());", inputs: { INPUT_1: "URLSearchParams", INPUT_2: "append" }, completeCode: "const p = new URLSearchParams(); p.append('active', 'true');" },
  { id: 13, title: "Axios params", stars: 2, category: "QUERY", description: "Axios serializa query params automáticamente.", objective: "Propiedad params", tags: ["params", "query string"], fileName: "axiosParams.js", completed: false, explanationText: "La opción params serializa objetos JS en formato ?key=value.", codeSnippet: "axios.get('/api/products', {\n  [INPUT_1]: { search: 'laptop', category: 'tech' }\n});", inputs: { INPUT_1: "params" }, completeCode: "params: { search: 'laptop', category: 'tech' }" },
  { id: 14, title: "Progreso de Upload", stars: 4, category: "UPLOAD", description: "Captura el progreso de subida de archivos.", objective: "onUploadProgress callback", tags: ["onUploadProgress", "progress"], fileName: "upload.js", completed: false, explanationText: "onUploadProgress expone loaded (bytes subidos) y total del archivo.", codeSnippet: "axios.post('/api/upload', formData, {\n  [INPUT_1]: (e) => {\n    const pct = Math.round((e.loaded * 100) / e.[INPUT_2]);\n  }\n});", inputs: { INPUT_1: "onUploadProgress", INPUT_2: "total" }, completeCode: "onUploadProgress: (e) => { Math.round((e.loaded * 100) / e.total); }" },
  { id: 15, title: "Instancia Personalizada de Axios", stars: 4, category: "CUSTOM", description: "Crea un cliente Axios aislado con baseURL propia.", objective: "axios.create()", tags: ["create", "baseURL", "instancia"], fileName: "client.js", completed: false, explanationText: "axios.create() genera un cliente REST aislado sin afectar el global.", codeSnippet: "const api = axios.[INPUT_1]({\n  [INPUT_2]: 'https://api.empresa.com/v1',\n  timeout: 3000\n});", inputs: { INPUT_1: "create", INPUT_2: "baseURL" }, completeCode: "const api = axios.create({ baseURL: '...', timeout: 3000 });" }
];

// ─── NODE.JS BACKEND (8 EJERCICIOS) ─────────────────────────────────────────
const NODEJS_EXERCISES = [
  { id: 1, title: "Módulos ES: import/export", stars: 1, category: "MODULES", description: "Exporta e importa funciones usando ES Modules.", objective: "import/export en Node.js", tags: ["import", "export", "ESM"], fileName: "math.mjs", completed: false, explanationText: "ES Modules usan import/export como estándar. Se habilitan con 'type: module' en package.json o extensión .mjs.", codeSnippet: "// math.mjs\n[INPUT_1] function add(a, b) { return a + b; }\n\n// app.mjs\n[INPUT_2] { add } from './math.mjs';", inputs: { INPUT_1: "export", INPUT_2: "import" }, completeCode: "export function add(a, b) { return a + b; }\nimport { add } from './math.mjs';" },
  { id: 2, title: "Express: Ruta GET básica", stars: 2, category: "EXPRESS", description: "Crea un endpoint GET que responda con JSON.", objective: "app.get() + res.json()", tags: ["Express", "GET", "JSON"], fileName: "server.js", completed: false, explanationText: "Express es el framework HTTP más popular de Node. app.get() define rutas que responden a peticiones GET.", codeSnippet: "import express from 'express';\nconst app = [INPUT_1]();\n\napp.[INPUT_2]('/api/users', (req, res) => {\n  res.[INPUT_3]([{ id: 1, name: 'Iram' }]);\n});\n\napp.listen([INPUT_4]);", inputs: { INPUT_1: "express", INPUT_2: "get", INPUT_3: "json", INPUT_4: "3000" }, completeCode: "app.get('/api/users', (req, res) => { res.json([...]); });\napp.listen(3000);" },
  { id: 3, title: "Middleware de Express", stars: 3, category: "MIDDLEWARE", description: "Crea un middleware que registre cada petición entrante.", objective: "app.use() con next()", tags: ["middleware", "use", "next"], fileName: "logger.js", completed: false, explanationText: "Los middlewares de Express interceptan el request pipeline. Deben llamar next() para continuar.", codeSnippet: "app.[INPUT_1]((req, res, [INPUT_2]) => {\n  console.log(`${req.[INPUT_3]} ${req.url}`);\n  [INPUT_4]();\n});", inputs: { INPUT_1: "use", INPUT_2: "next", INPUT_3: "method", INPUT_4: "next" }, completeCode: "app.use((req, res, next) => { console.log(req.method, req.url); next(); });" },
  { id: 4, title: "Variables de Entorno con dotenv", stars: 2, category: "CONFIG", description: "Carga variables de entorno de forma segura sin hardcodear secretos.", objective: "process.env con dotenv", tags: ["dotenv", "process.env", "secrets"], fileName: "config.js", completed: false, explanationText: "dotenv carga variables de un archivo .env en process.env. Nunca commitees .env a git.", codeSnippet: "import 'dotenv/config';\n\nconst dbUrl = [INPUT_1].env.[INPUT_2];\nconst port = process.[INPUT_3].PORT || 3000;", inputs: { INPUT_1: "process", INPUT_2: "DATABASE_URL", INPUT_3: "env" }, completeCode: "const dbUrl = process.env.DATABASE_URL;" },
  { id: 5, title: "Async Error Handling en Express", stars: 3, category: "ERRORS", description: "Captura errores asíncronos en rutas de Express.", objective: "try/catch en async handlers", tags: ["async", "try/catch", "error handler"], fileName: "errors.js", completed: false, explanationText: "Express no captura errores de async handlers automáticamente. Usa try/catch y next(err).", codeSnippet: "app.get('/api/data', async (req, res, [INPUT_1]) => {\n  [INPUT_2] {\n    const data = await fetchData();\n    res.json(data);\n  } [INPUT_3] (err) {\n    [INPUT_4](err);\n  }\n});", inputs: { INPUT_1: "next", INPUT_2: "try", INPUT_3: "catch", INPUT_4: "next" }, completeCode: "try { ... } catch (err) { next(err); }" },
  { id: 6, title: "fs.readFile: Lectura Asíncrona", stars: 2, category: "FS", description: "Lee archivos del sistema de forma asíncrona con fs/promises.", objective: "fs/promises API", tags: ["fs", "readFile", "promises"], fileName: "reader.mjs", completed: false, explanationText: "fs/promises expone las operaciones del filesystem como promesas async/await.", codeSnippet: "import { [INPUT_1] } from 'node:fs/promises';\n\nconst content = [INPUT_2] readFile('./data.json', '[INPUT_3]');\nconst data = JSON.[INPUT_4](content);", inputs: { INPUT_1: "readFile", INPUT_2: "await", INPUT_3: "utf-8", INPUT_4: "parse" }, completeCode: "const content = await readFile('./data.json', 'utf-8');" },
  { id: 7, title: "Router modular de Express", stars: 3, category: "ROUTES", description: "Organiza rutas en módulos separados usando express.Router().", objective: "Modularización con Router", tags: ["Router", "modular", "express"], fileName: "userRoutes.js", completed: false, explanationText: "express.Router() crea un mini-aplicación de rutas que se monta en el app principal.", codeSnippet: "import { [INPUT_1] } from 'express';\nconst router = [INPUT_2]();\n\nrouter.get('/', (req, res) => res.json([]));\nrouter.post('/', (req, res) => res.status(201).json(req.body));\n\nexport default [INPUT_3];", inputs: { INPUT_1: "Router", INPUT_2: "Router", INPUT_3: "router" }, completeCode: "const router = Router();\nexport default router;" },
  { id: 8, title: "package.json: Scripts y Type Module", stars: 1, category: "CONFIG", description: "Configura scripts de npm y habilita ES Modules en package.json.", objective: "Scripts npm y ESM", tags: ["scripts", "type: module"], fileName: "package.json", completed: false, explanationText: "\"type\": \"module\" habilita import/export. Los scripts de npm se ejecutan con 'npm run <name>'.", codeSnippet: "{\n  \"name\": \"my-api\",\n  \"[INPUT_1]\": \"module\",\n  \"scripts\": {\n    \"dev\": \"node --watch server.mjs\",\n    \"[INPUT_2]\": \"node server.mjs\"\n  }\n}", inputs: { INPUT_1: "type", INPUT_2: "start" }, completeCode: "\"type\": \"module\", \"scripts\": { \"dev\": \"...\", \"start\": \"...\" }" }
];

// ─── E2E TESTING: Cypress / Playwright (6 EJERCICIOS) ───────────────────────
const E2E_EXERCISES = [
  { id: 1, title: "Cypress: Visitar y Verificar Título", stars: 1, category: "CYPRESS", description: "Navega a una URL y verifica que el título de la página sea correcto.", objective: "cy.visit() y cy.title()", tags: ["cy.visit", "cy.title", "E2E"], fileName: "home.cy.ts", completed: false, explanationText: "cy.visit() navega a la URL. cy.title() obtiene el título del documento para hacer aserciones.", codeSnippet: "describe('Home', () => {\n  it('has correct title', () => {\n    cy.[INPUT_1]('/');\n    cy.[INPUT_2]().should('[INPUT_3]', 'Mi App');\n  });\n});", inputs: { INPUT_1: "visit", INPUT_2: "title", INPUT_3: "contain" }, completeCode: "cy.visit('/'); cy.title().should('contain', 'Mi App');" },
  { id: 2, title: "Cypress: Interacción con Formularios", stars: 2, category: "CYPRESS", description: "Selecciona un input, escribe texto y envía un formulario.", objective: "cy.get(), .type() y .click()", tags: ["cy.get", "type", "click"], fileName: "login.cy.ts", completed: false, explanationText: "cy.get() selecciona elementos por selector CSS. .type() simula escritura del usuario.", codeSnippet: "cy.[INPUT_1]('[data-testid=email]').[INPUT_2]('iram@test.com');\ncy.get('[data-testid=password]').type('pass123');\ncy.get('[data-testid=submit]').[INPUT_3]();\ncy.url().should('[INPUT_4]', '/dashboard');", inputs: { INPUT_1: "get", INPUT_2: "type", INPUT_3: "click", INPUT_4: "include" }, completeCode: "cy.get('[data-testid=email]').type('...');\ncy.get('[data-testid=submit]').click();" },
  { id: 3, title: "Cypress: Interceptar Peticiones HTTP", stars: 3, category: "CYPRESS", description: "Intercepta llamadas HTTP para mockear respuestas del backend.", objective: "cy.intercept() para mocking de red", tags: ["intercept", "fixture", "mock"], fileName: "api.cy.ts", completed: false, explanationText: "cy.intercept() intercepta requests de red para retornar datos de prueba sin depender del backend real.", codeSnippet: "cy.[INPUT_1]('GET', '/api/users', {\n  [INPUT_2]: 'users.json'\n}).as('getUsers');\n\ncy.visit('/users');\ncy.[INPUT_3]('@getUsers');", inputs: { INPUT_1: "intercept", INPUT_2: "fixture", INPUT_3: "wait" }, completeCode: "cy.intercept('GET', '/api/users', { fixture: 'users.json' }).as('getUsers');\ncy.wait('@getUsers');" },
  { id: 4, title: "Playwright: Navegación y Assertions", stars: 2, category: "PLAYWRIGHT", description: "Navega a una URL y verifica contenido visible con Playwright.", objective: "page.goto() y expect()", tags: ["goto", "toBeVisible", "Playwright"], fileName: "home.spec.ts", completed: false, explanationText: "Playwright usa async/await nativo. expect().toBeVisible() verifica que un elemento sea visible en la página.", codeSnippet: "import { test, [INPUT_1] } from '@playwright/test';\n\ntest('home page', async ({ page }) => {\n  await page.[INPUT_2]('/');\n  await expect(page.[INPUT_3]('h1')).[INPUT_4]();\n});", inputs: { INPUT_1: "expect", INPUT_2: "goto", INPUT_3: "locator", INPUT_4: "toBeVisible" }, completeCode: "await page.goto('/');\nawait expect(page.locator('h1')).toBeVisible();" },
  { id: 5, title: "Playwright: Llenar Formularios", stars: 3, category: "PLAYWRIGHT", description: "Interactúa con inputs y botones usando locators de Playwright.", objective: "page.fill() y page.click()", tags: ["fill", "click", "locator"], fileName: "form.spec.ts", completed: false, explanationText: "Playwright recomienda locators semánticos como getByRole y getByLabel para tests más resilientes.", codeSnippet: "test('login', async ({ page }) => {\n  await page.goto('/login');\n  await page.[INPUT_1]('[data-testid=email]', 'iram@test.com');\n  await page.fill('[data-testid=pass]', 'secret');\n  await page.[INPUT_2]('[data-testid=submit]');\n  await expect(page).toHaveURL(/[INPUT_3]/);\n});", inputs: { INPUT_1: "fill", INPUT_2: "click", INPUT_3: "dashboard" }, completeCode: "await page.fill(selector, value);\nawait page.click(selector);" },
  { id: 6, title: "Playwright: Mocking de API Routes", stars: 4, category: "PLAYWRIGHT", description: "Intercepta y mockea respuestas de API con page.route().", objective: "page.route() para mock de red", tags: ["route", "fulfill", "mock"], fileName: "mock.spec.ts", completed: false, explanationText: "page.route() intercepta peticiones y permite retornar respuestas mockeadas con route.fulfill().", codeSnippet: "await page.[INPUT_1]('/api/users', async route => {\n  await route.[INPUT_2]({\n    [INPUT_3]: 'application/json',\n    body: JSON.stringify([{ id: 1, name: 'Test' }])\n  });\n});", inputs: { INPUT_1: "route", INPUT_2: "fulfill", INPUT_3: "contentType" }, completeCode: "await page.route('/api/users', async route => {\n  await route.fulfill({ contentType: '...', body: '...' });\n});" }
];

// ─── GIT & DEVOPS (8 EJERCICIOS) ────────────────────────────────────────────
const GIT_EXERCISES = [
  { id: 1, title: "Git: Crear y Cambiar de Rama", stars: 1, category: "BRANCHES", description: "Crea una nueva rama y cámbiate a ella con un solo comando.", objective: "git checkout -b / git switch -c", tags: ["branch", "checkout", "switch"], fileName: "terminal", completed: false, explanationText: "git switch -c crea y cambia a una nueva rama en un solo paso. Es el reemplazo moderno de checkout -b.", codeSnippet: "git [INPUT_1] -c feature/login\n\n# Equivalente antiguo:\ngit checkout [INPUT_2] feature/login", inputs: { INPUT_1: "switch", INPUT_2: "-b" }, completeCode: "git switch -c feature/login\ngit checkout -b feature/login" },
  { id: 2, title: "Git: Stage, Commit y Push", stars: 1, category: "BASICS", description: "Agrega cambios al staging, crea un commit y envíalos al remoto.", objective: "Flujo básico de git", tags: ["add", "commit", "push"], fileName: "terminal", completed: false, explanationText: "git add agrega al staging area. git commit crea un snapshot. git push envía al repositorio remoto.", codeSnippet: "git [INPUT_1] .\ngit [INPUT_2] -m 'feat: add login page'\ngit [INPUT_3] origin main", inputs: { INPUT_1: "add", INPUT_2: "commit", INPUT_3: "push" }, completeCode: "git add . && git commit -m 'msg' && git push origin main" },
  { id: 3, title: "Git: Rebase Interactivo", stars: 4, category: "REBASE", description: "Reorganiza commits antes de hacer merge para mantener historial limpio.", objective: "git rebase para historial lineal", tags: ["rebase", "squash", "fixup"], fileName: "terminal", completed: false, explanationText: "Rebase mueve tu rama encima de otra, creando un historial lineal sin merge commits.", codeSnippet: "# Actualizar tu rama con main\ngit [INPUT_1] main\n\n# Squash últimos 3 commits\ngit rebase -i [INPUT_2]~3", inputs: { INPUT_1: "rebase", INPUT_2: "HEAD" }, completeCode: "git rebase main\ngit rebase -i HEAD~3" },
  { id: 4, title: "Git: Resolver Conflictos", stars: 3, category: "CONFLICTS", description: "Identifica y resuelve marcadores de conflicto de merge.", objective: "Conflict markers", tags: ["conflict", "merge", "resolve"], fileName: "file.ts", completed: false, explanationText: "Git marca conflictos con <<<<<<< HEAD, =======, y >>>>>>> branch. Debes elegir qué código conservar.", codeSnippet: "<<<<<<< HEAD\nconst api = '[INPUT_1]';\n=======\nconst api = 'https://staging.api.com';\n>>>>>>> feature/new-api\n\n// Después de resolver: quitar [INPUT_2] y elegir la versión correcta", inputs: { INPUT_1: "https://api.prod.com", INPUT_2: "marcadores" }, completeCode: "Eliminar <<<<<<< HEAD, =======, >>>>>>> y conservar el código correcto." },
  { id: 5, title: "Conventional Commits", stars: 2, category: "COMMITS", description: "Sigue la convención de commits semánticos para mensajes claros.", objective: "Prefijos feat/fix/chore/docs", tags: ["conventional", "feat", "fix"], fileName: "terminal", completed: false, explanationText: "Conventional Commits estandariza mensajes: tipo(scope): descripción. Facilita changelogs y semantic versioning.", codeSnippet: "# Nueva funcionalidad\ngit commit -m '[INPUT_1]: add user authentication'\n\n# Corrección de bug\ngit commit -m '[INPUT_2]: resolve null pointer in login'\n\n# Refactoring sin cambio funcional\ngit commit -m '[INPUT_3]: extract auth middleware'", inputs: { INPUT_1: "feat", INPUT_2: "fix", INPUT_3: "refactor" }, completeCode: "feat: ..., fix: ..., refactor: ..." },
  { id: 6, title: ".gitignore: Excluir Archivos", stars: 1, category: "CONFIG", description: "Configura .gitignore para excluir archivos sensibles y generados.", objective: "Patrones de exclusión", tags: [".gitignore", "node_modules", ".env"], fileName: ".gitignore", completed: false, explanationText: ".gitignore evita que archivos sensibles o generados entren al repositorio.", codeSnippet: "# Dependencias\n[INPUT_1]/\n\n# Variables de entorno\n[INPUT_2]\n.env.local\n\n# Build output\n[INPUT_3]/", inputs: { INPUT_1: "node_modules", INPUT_2: ".env", INPUT_3: "dist" }, completeCode: "node_modules/\n.env\ndist/" },
  { id: 7, title: "GitHub Actions: CI Básico", stars: 4, category: "CI/CD", description: "Crea un workflow de GitHub Actions que ejecute tests en cada push.", objective: "Configurar CI con GitHub Actions", tags: ["actions", "workflow", "CI"], fileName: "ci.yml", completed: false, explanationText: "GitHub Actions automatiza tareas como tests, build y deploy usando archivos YAML en .github/workflows/.", codeSnippet: "name: CI\non: [push, pull_request]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/[INPUT_1]@v4\n      - uses: actions/setup-node@v4\n        with:\n          node-version: 20\n      - run: npm [INPUT_2]\n      - run: npm [INPUT_3]", inputs: { INPUT_1: "checkout", INPUT_2: "ci", INPUT_3: "test" }, completeCode: "actions/checkout@v4, npm ci, npm test" },
  { id: 8, title: "ESLint + Prettier: Configuración", stars: 3, category: "QUALITY", description: "Configura ESLint y Prettier para mantener código consistente.", objective: "Linting y formatting automático", tags: ["ESLint", "Prettier", "config"], fileName: "eslint.config.js", completed: false, explanationText: "ESLint detecta errores y malas prácticas. Prettier formatea automáticamente. Juntos aseguran calidad de código.", codeSnippet: "import eslint from '@eslint/js';\nimport prettier from 'eslint-config-prettier';\n\nexport default [\n  eslint.configs.[INPUT_1],\n  [INPUT_2],\n  {\n    rules: {\n      'no-unused-vars': '[INPUT_3]'\n    }\n  }\n];", inputs: { INPUT_1: "recommended", INPUT_2: "prettier", INPUT_3: "warn" }, completeCode: "eslint.configs.recommended, prettier, 'no-unused-vars': 'warn'" }
];

// ─── CATÁLOGO DE MÓDULOS ────────────────────────────────────────────────────
const ALL_MODULES = [
  { key: 'vue', name: 'Vue 3 Composition API', icon: '⚡', badge: 'Frontend', color: 'emerald', desc: 'Componentes, reactividad, emits, props, composables y slots.', topics: ['ref', 'computed', 'watch', 'emits', 'composables'], exercises: VUE_EXERCISES },
  { key: 'pinia', name: 'Pinia State Management', icon: '🍍', badge: 'State', color: 'yellow', desc: 'Stores, getters, actions, storeToRefs y persistencia.', topics: ['defineStore', 'actions', 'getters', '$subscribe'], exercises: PINIA_EXERCISES },
  { key: 'firebase', name: 'Firebase Platform', icon: '🔥', badge: 'BaaS', color: 'orange', desc: 'Auth, Firestore, Cloud Functions, Security Rules y App Check.', topics: ['Auth', 'Firestore', 'Functions', 'Rules'], exercises: FIREBASE_EXERCISES },
  { key: 'typescript', name: 'TypeScript Core', icon: '💙', badge: 'Typing', color: 'blue', desc: 'Interfaces, generics, utility types, enums y array methods.', topics: ['interface', 'generics', 'Pick', 'enum'], exercises: TYPESCRIPT_EXERCISES },
  { key: 'sql', name: 'SQL Server Pro', icon: '🗄️', badge: 'Database', color: 'cyan', desc: 'JOINS, funciones, índices, triggers, vistas y seguridad RLS.', topics: ['JOINS', 'INDEX', 'TRIGGER', 'RLS'], exercises: SQL_EXERCISES },
  { key: 'vitest', name: 'Vitest & Testing', icon: '🧪', badge: 'QA', color: 'amber', desc: 'Aserciones, mocks, async, VTU, snapshots y store testing.', topics: ['toBe', 'vi.fn', 'mount', 'snapshot'], exercises: VITEST_EXERCISES },
  { key: 'security', name: 'Security: OAuth2 & JWT', icon: '🔑', badge: 'Security', color: 'purple', desc: 'JWT, PKCE, CORS, CSP, HTTPS, Firebase Rules y XSS defense.', topics: ['JWT', 'PKCE', 'CORS', 'CSP'], exercises: SECURITY_EXERCISES },
  { key: 'api', name: 'Axios & Fetch API', icon: '🌐', badge: 'HTTP', color: 'rose', desc: 'GET, POST, error handling, interceptors, abort y progress.', topics: ['fetch', 'axios', 'interceptors', 'AbortController'], exercises: API_EXERCISES },
  { key: 'nodejs', name: 'Node.js Backend', icon: '🟢', badge: 'Backend', color: 'lime', desc: 'Express, middlewares, routing, fs, dotenv y error handling.', topics: ['Express', 'middleware', 'Router', 'ESM'], exercises: NODEJS_EXERCISES },
  { key: 'e2e', name: 'E2E: Cypress & Playwright', icon: '🎭', badge: 'E2E', color: 'pink', desc: 'Navegación, formularios, intercept, route y mocking de red.', topics: ['cy.visit', 'page.goto', 'intercept', 'route'], exercises: E2E_EXERCISES },
  { key: 'git', name: 'Git & DevOps', icon: '🔧', badge: 'DevOps', color: 'slate', desc: 'Branches, rebase, conflicts, conventional commits y CI/CD.', topics: ['branch', 'rebase', 'actions', 'ESLint'], exercises: GIT_EXERCISES }
];
